#!/bin/bash
##############################################################################
# ESG Federation download script
#
# Template version: 1.2
# Generated by esg-dn1.nsc.liu.se - 2023/02/21 12:49:34
# Search URL: http://esg-dn1.nsc.liu.se/esg-search/wget/?distrib=false&dataset_id=CMIP6.RFMIP.EC-Earth-Consortium.EC-Earth3.piClim-control.r2i1p1f1.Amon.rsut.gr.v20211201|esg-dn2.nsc.liu.se
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############" 
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=1.3.2
CACHE_FILE=.$(basename $0).status
openId=
search_url='http://esg-dn1.nsc.liu.se/esg-search/wget/?distrib=false&dataset_id=CMIP6.RFMIP.EC-Earth-Consortium.EC-Earth3.piClim-control.r2i1p1f1.Amon.rsut.gr.v20211201|esg-dn2.nsc.liu.se'

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185001-185012.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185001-185012.nc' 'SHA256' 'a2946c8809c22cbbda0d30ad25ef979fe12ca5cf9d2a164efbc2d09a5ea1af94'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185101-185112.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185101-185112.nc' 'SHA256' '675b18b5b987be3d6a931fbbaeccbf769a00b7afe77b91fbbe47733e7f1fa05b'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185201-185212.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185201-185212.nc' 'SHA256' 'ef545547d1dc5a97557ab9b8ea5b9e88951cd28635d80c8c0f5d4599d3bf9b13'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185301-185312.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185301-185312.nc' 'SHA256' '52e0555804c6c8cf1dbbbaf1a5736250463ad255961dba95ff5ac85c851138f2'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185401-185412.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185401-185412.nc' 'SHA256' 'e8365b57b7063e5e5c865a9bfba7e7ffef48d6184e372ca2fdd5e8be03bd2fcf'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185501-185512.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185501-185512.nc' 'SHA256' '495c9f5d781a590716b69e672fb56a63bc5bfb666b0f34ded5263f783bc77aa5'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185601-185612.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185601-185612.nc' 'SHA256' '66d6601378ee6186232dbfca89c1525982dfb1cb80087a8c44f87f09c02f3877'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185701-185712.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185701-185712.nc' 'SHA256' 'ce455a99b4c92ba147636fd8dc7fc916a5d5f46dd49bffb5f25fc2111caeea78'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185801-185812.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185801-185812.nc' 'SHA256' '15646c24695bb728f6cedaff201e6cee029dc15b3e7c37d29977e5eb3a30e5b1'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185901-185912.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185901-185912.nc' 'SHA256' '357a901fa7651d4a9177321d8120bc4881d486e4c586d74bfec2c04531c33ed0'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186001-186012.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186001-186012.nc' 'SHA256' '97683d84d78bd5cf57f0d7dc72c66d78ac13a3fc33174ec463ac2573aaeac526'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186101-186112.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186101-186112.nc' 'SHA256' '54ff66c339e7a5806a09c8375118b4a0e86499cc1069945113f24a46d956f39e'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186201-186212.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186201-186212.nc' 'SHA256' '5424fdfe6cfcdf9cdd9c6a55046a64933bd6077845c44305f134d9f1e76afd13'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186301-186312.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186301-186312.nc' 'SHA256' '9b2b9d838f24b5ad57487ed40ed5b4c4d36c0c188353b0651abcd76ec3d9d380'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186401-186412.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186401-186412.nc' 'SHA256' '3462f58c01a9274e5b2e5de41a6d8feb21966156db011b54ec94eb8815f6d7ea'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186501-186512.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186501-186512.nc' 'SHA256' 'c8813f7b05fac84ad1c00e6b13064ec11d079f1fa4a7faae713664277afbc50c'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186601-186612.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186601-186612.nc' 'SHA256' '5f998b043c3b729fb81f5ea6faac8bb5a83b4ba61d157f24929b3b332c214039'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186701-186712.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186701-186712.nc' 'SHA256' 'd8d0568507a5de65f272b0d312d24ccb08684e51841d58862d79ed78a61cc2be'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186801-186812.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186801-186812.nc' 'SHA256' 'a6e9a7d68a14393e0dfc0a6d55c58d2b0af4fafe7507944112cacc8a3f8f0427'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186901-186912.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186901-186912.nc' 'SHA256' '31b1c531f0eabcf820ea33d404b1fd895f456abe6def0f767cb44b13aae53bfe'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187001-187012.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187001-187012.nc' 'SHA256' '445bc7da487c6463dfd10f84300d3c4331b881f7329e15c2833c5e80447341ba'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187101-187112.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187101-187112.nc' 'SHA256' 'c5fbde37b6f5c9dee6061fbe958098bea5c57e9cf8a99bde480da3f04e22e4b0'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187201-187212.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187201-187212.nc' 'SHA256' '6966ae5e712f425c864ffb5b253c3354dabd41d4dedd0f9ad1c849ac7d8f6376'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187301-187312.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187301-187312.nc' 'SHA256' '51bb0524ce9a29f39786a3cad13ce9859c42490b6810dd9345f976e88550db42'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187401-187412.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187401-187412.nc' 'SHA256' '8476b63987f66f0069e39e434d580604ce7e8fc15834ea26350ce0bd2b32355d'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187501-187512.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187501-187512.nc' 'SHA256' '913a26d239ef061704a5d2227d471be42fed004dd235300366119f17f2d17c4f'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187601-187612.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187601-187612.nc' 'SHA256' '29684fb9b12cc779d8c4a44d2785d3738c4c5089fbfc797e3a5d1448a209806e'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187701-187712.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187701-187712.nc' 'SHA256' 'b4a383cee536843d6e8425b324353e576f89b193be14940b977e0c33e84b8409'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187801-187812.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187801-187812.nc' 'SHA256' '6b81a21344fe520d99d05aa052309294614498a6a67cd228d4a271778221b41c'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187901-187912.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187901-187912.nc' 'SHA256' '0a41c79a8f13d05d82b75a3b6c8d2a4b7ac5567dfe636034d4e4ca2e248f3731'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188001-188012.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188001-188012.nc' 'SHA256' 'ba0d5f0ef1e3deddc67ca9f0a03c09947b0ba5a36bb99475be03ce9322a69636'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188101-188112.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188101-188112.nc' 'SHA256' '5c2295ff6f458536a9ad29ce754c9a505d46b248970f12f96ce1262055ef55a5'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188201-188212.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188201-188212.nc' 'SHA256' '53c591fc0d7b53b584f1ac40aed513da5aa8859a93b6355c11099692b4d102e2'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188301-188312.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188301-188312.nc' 'SHA256' '1e98a2a0bf4a7bed9a89ab99b7c0af25f696d947aa56db74ec8fbbf02af8fff3'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188401-188412.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188401-188412.nc' 'SHA256' '6f9308e54546666cc21b6cc5350c6fa87f48a11d48aff4ac1505f1bcc248c0dd'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188501-188512.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188501-188512.nc' 'SHA256' '32210a107338ea4b386b428785d742408a0113260a8ed404e68d5b3f47689133'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188601-188612.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188601-188612.nc' 'SHA256' '794568085da32de37664c8d819125158473b59829d12159b5eeabef495e3f5c5'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188701-188712.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188701-188712.nc' 'SHA256' '424205b0d4561b1902ab810e89a12b4c6668d33ac0bf57534f3ba8623aa1451b'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188801-188812.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188801-188812.nc' 'SHA256' 'fef1f547be3b5c3499acb8dd0365de03af40c23378c529ee8bc991f093b6fec8'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188901-188912.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188901-188912.nc' 'SHA256' '25e7f67e136e694dd1705fa2c2c35520aec2b52d0aeba332e82c841f168c79e1'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189001-189012.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189001-189012.nc' 'SHA256' '6f08c517bfacec773c5a09937ac8f56ad144038c38fb919e385259d973e284a8'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189101-189112.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189101-189112.nc' 'SHA256' '5b7b3c334763d3e30c951e3511a1417275d1a103e6369fabbf231b200f0c3c45'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189201-189212.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189201-189212.nc' 'SHA256' '649705d72db560e7ca1b087c50925ef1d4628691f7b52db384e23cc623cc9f5c'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189301-189312.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189301-189312.nc' 'SHA256' '146ec689d75e4e882d712d36288a6a722113ace21fda971481d9c95d1a182ee9'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189401-189412.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189401-189412.nc' 'SHA256' '9f45ff2c65d233ad36b1313e3072f43d2cee971e90ab1a851acc5bf6e5e2a08c'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189501-189512.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189501-189512.nc' 'SHA256' '2b9e0e2a317df99ec7e7a034ce85e7095cd531fd6681812606e60e02eb9de32c'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189601-189612.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189601-189612.nc' 'SHA256' 'a488e3de9f793dcfbaf5c4d391b5c7baee71a1b25449f8d32cd22974ccd331ba'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189701-189712.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189701-189712.nc' 'SHA256' '84ff7af708e8c044c4e467bf66d64bcfbb0c24cab3c88361cbf922111919bd9f'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189801-189812.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189801-189812.nc' 'SHA256' 'baae7db8981ac940c1c186da6a81ca76c55fd866704d9485a48a65955e66e49f'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189901-189912.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189901-189912.nc' 'SHA256' 'f65af1bf61ac58ccedcd648659814acd69044bf9801007e492922aee1432eb1a'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190001-190012.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190001-190012.nc' 'SHA256' '4d6ef1a10ec96b3bd0dbb6cdc304f091f3363e282c0d5afd5d4f0281394e99ba'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190101-190112.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190101-190112.nc' 'SHA256' 'df4dbf5066436c06e350e5cb5d7e8b9404ccd3e45abe9f6d56a01e4ddb1d9f99'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190201-190212.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190201-190212.nc' 'SHA256' '8ad41629791b7f7ca433774d8c4b07009cc6587b2739bf356e6eda65ec6b23be'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190301-190312.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190301-190312.nc' 'SHA256' '86d89ae0ac8e036ecce0f3b508b653d005cc72f8ea3f59d44c98ebcded4fe78d'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190401-190412.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190401-190412.nc' 'SHA256' 'b1d70bd063bd69f12ec927e0b70c4550bf1fcc43e9910aa552c32ec8f963fc79'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190501-190512.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190501-190512.nc' 'SHA256' 'ad8cb6cc13d64a604e7c0a87458521daf2e0f7df6976daf79575bdde5dc60b96'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190601-190612.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190601-190612.nc' 'SHA256' 'f82c8c3255c4909febfc29cd9efc7a84b7a366121c398f60f9057ee3dee3a198'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190701-190712.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190701-190712.nc' 'SHA256' '39b41757080b5cee6c78f77dcc6d4bd3ab9edea95a62174bad6d36fe0449a4e5'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190801-190812.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190801-190812.nc' 'SHA256' 'a1c0e43a68ca3cd73b77bbdba1cebdd5277d867fdf137b7a7ba1ef83497d36b8'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190901-190912.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190901-190912.nc' 'SHA256' 'c505989237e45be56920e4ac6756693225db79e53a7d7fc54f177aeb01ec71d3'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191001-191012.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191001-191012.nc' 'SHA256' '08292d6c0b15591d86550e28cb6ec4057aae75b7615816697d887fbe3fe075ff'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191101-191112.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191101-191112.nc' 'SHA256' '8c6328e60efae482f21639beb1d54474551be0def170917cd4a84dea5482ff69'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191201-191212.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191201-191212.nc' 'SHA256' '56329fffd8c5e2f59a86a0585a2335686bc392b86e34893eda559b4ba275f5ea'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191301-191312.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191301-191312.nc' 'SHA256' '95909fa921837ac86d886c0e72ac252a7327ea0ab5941881e54cbefde223afc3'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191401-191412.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191401-191412.nc' 'SHA256' '03c63d95e09fc66c4e62c23a02b4737685f5ea941d45a51705e8c079303033d5'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191501-191512.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191501-191512.nc' 'SHA256' '95fc95923f9d56767154fbf48791976febdf1d76bcb04460d5ef4b7b8e473536'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191601-191612.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191601-191612.nc' 'SHA256' 'b3f2ae719cb975a739ebc1999a8f2d2bb0b4981f048c2437b0629ffd8b590d79'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191701-191712.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191701-191712.nc' 'SHA256' 'feccd1370a9d0b6f60eaa1dd38700e999fd3a6f558d66bc89c4f9a46b27cb398'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191801-191812.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191801-191812.nc' 'SHA256' '0d2dd6a4bd06287e8166a2b479156c7861da91c28daf46fb0cb9b043aadc5115'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191901-191912.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191901-191912.nc' 'SHA256' '2d8efae96b371980ab0993e4afabf1c73d3e44c4911fac0a39dc155ba0683381'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192001-192012.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192001-192012.nc' 'SHA256' '3523c6ad831b43e66332bfc3ce29a5a64994a7d649d805f5c8d0f09555257382'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192101-192112.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192101-192112.nc' 'SHA256' 'bdcb30fea2ebb076b055567ad17fc32888f4c6a7887a471dc64437be82c10d20'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192201-192212.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192201-192212.nc' 'SHA256' '6c12634ed1b7e23e8f2369fb08a2ef824a5b70843244f9c3d62167c8559f737f'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192301-192312.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192301-192312.nc' 'SHA256' '2fc955b1ff1a8d5f962b7c89517f50b93ea37176365ce165d4fede1ad5356588'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192401-192412.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192401-192412.nc' 'SHA256' 'f2a7bf038655fa491bac8a994b084f3afcc4490f4934f6339cbcdaa28d24d197'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192501-192512.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192501-192512.nc' 'SHA256' 'd4260bd7938b225d115277414ab5644aaa76c362766567ce0f561a0047bf0510'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192601-192612.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192601-192612.nc' 'SHA256' 'b58e12cc568e533da12cbddbe8b3d520f9358e79c5dd245e77c02ec1c3f6ad61'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192701-192712.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192701-192712.nc' 'SHA256' 'aab8bd88308ea682dde57f79f2d965f71399352502b9587bb9b91f5af3c5b397'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192801-192812.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192801-192812.nc' 'SHA256' 'c57bd08badb470a83c79415daa47be5608d9fd4474c44f47526646eb3932d9e1'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192901-192912.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192901-192912.nc' 'SHA256' '665505f86fde7b051af1b7e6bdab7d10274c9038ffc7340d78e7ef6a999d077b'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193001-193012.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193001-193012.nc' 'SHA256' '1b7dcfe9d3f4b493d876fd86dccf52e656c3c880120b7912a7cad2993d498712'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193101-193112.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193101-193112.nc' 'SHA256' 'c3d1b6b62c460314fbdcdb107da30e2c86900ec24f103b64bc391b29eafd49be'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193201-193212.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193201-193212.nc' 'SHA256' 'c7f53f9781d84786c318226ab655acdaea1a0080326bc251925494f44f0e1d1f'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193301-193312.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193301-193312.nc' 'SHA256' 'b001725a4fb84bb2e075f4787a9496a0127beb44d2c36b24012e5539cc9d0146'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193401-193412.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193401-193412.nc' 'SHA256' 'd8724115fc2816bd1c64a44a57fbf3e936ee42fbea4a16e513c944f719b79ebb'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193501-193512.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193501-193512.nc' 'SHA256' '76238a6fdc62d5717418cb043f452f3a549b1c9e6f181d9b5fe62bf873eccacb'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193601-193612.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193601-193612.nc' 'SHA256' 'f3ca48187e3db02c009dcf531223d95f86e6eaf88d1a847a642a71fac7d5fcba'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193701-193712.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193701-193712.nc' 'SHA256' '075447fd645c4fdb0c57def90467495d1443b7f726c110d7563c166e5d07a1f6'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193801-193812.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193801-193812.nc' 'SHA256' 'dc9363b156e978bc935a19a0e842df961f2c41f9aa34de8a30347b4eddd9aec4'
'rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193901-193912.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsut/gr/v20211201/rsut_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193901-193912.nc' 'SHA256' '28eed75c778f8b4c3723a3ef5877a43607bf56df7f8cf22bfe0e2e1cd3d96133'
EOF--dataset.file.url.chksum_type.chksum
)"

# ESG_HOME should point to the directory containing ESG credentials.
#   Default is $HOME/.esg
ESG_HOME=${ESG_HOME:-$HOME/.esg}
[[ -d $ESG_HOME ]] || mkdir -p $ESG_HOME

ESG_CREDENTIALS=${X509_USER_PROXY:-$ESG_HOME/credentials.pem}
ESG_CERT_DIR=${X509_CERT_DIR:-$ESG_HOME/certificates}
MYPROXY_STATUS=$HOME/.MyProxyLogon
COOKIE_JAR=$ESG_HOME/cookies
MYPROXY_GETCERT=$ESG_HOME/getcert.jar
CERT_EXPIRATION_WARNING=$((60 * 60 * 8))   #Eight hour (in seconds)

WGET_TRUSTED_CERTIFICATES=$ESG_HOME/certificates


# Configure checking of server SSL certificates.
#   Disabling server certificate checking can resolve problems with myproxy
#   servers being out of sync with datanodes.
CHECK_SERVER_CERT=${CHECK_SERVER_CERT:-Yes}

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags] [openid] [username]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
    echo "For more information check the website: http://esgf.org/wiki/ESGF_wget"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts ':c:pfF:o:w:isuUndvqhHI:T' OPT; do
    case $OPT in
        H) skip_security=1 && use_http_sec=1;; #       : Authenticate with OpenID (username,) and password, without the need for a certificate.
        T) force_TLSv1=1;;              #       : Forces wget to use TLSv1. 
        c) ESG_CREDENTIALS="$OPTARG";;  #<cert> : use this certificate for authentication.
        f) force=1;;                    #       : force certificate retrieval (defaults to only once per day); for certificate-less authentication (see -H option), this flag will force login and refresh cookies.
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        o) openId="$OPTARG";;           #<openid>: Provide OpenID instead of interactively asking for it.
        I) username_supplied="$OPTARG";;    #<user_id> : Explicitly set user ID.  By default, the user ID is extracted from the last component of the OpenID URL.  Use this flag to override this behaviour.                   
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        s) skip_security=1 && use_cookies_for_http_basic_auth_start=1;;            #       : completely skip security. It will only work if the accessed data is not secured at all. -- works only if the accessed data is unsecured or a certificate exists or cookies are saved (latter applies to -H option only).
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi


#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    new_wget="$(wget "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0      
fi


##############################################################################
check_java() {
    if ! type java >& /dev/null; then
        echo "Java could not be found." >&2
        return 1
    fi
    if java -version 2>&1|grep openjdk >/dev/null; then
        openjdk=1;
    else
        openjdk=0;
    fi
    jversion=($(jversion=$(java -version 2>&1 | awk '/version/ {gsub("\"","");print $3}'); echo ${jversion//./ }))
    mVer=${jversion[1]}
    if [ $openjdk -eq 1 ]; then
        mVer=${jversion[0]}
        if ((mVer<5)); then
            echo "Openjdk detected. Version 9+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    else
    
        if ((mVer<5)); then
            echo "Java version 1.5+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    fi
}

check_myproxy_logon() {
    if ! type myproxy-logon >& /dev/null; then
	echo "myproxy-logon could not be found." >&2
	return 1
    fi
    echo "myproxy-logon found" >&2
}

proxy_to_java() {
    local proxy_user proxy_pass proxy_server proxy_port
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$http_proxy)
    local JAVA_PROXY=
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyPort=$proxy_port"
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$https_proxy)
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyPort=$proxy_port"
    
    echo "$JAVA_PROXY"
}

# get certificates from github
get_certificates() {
    # don't if this was already done today
    [[ -z $force && "$(find $ESG_CERT_DIR -type d -mtime -1 2>/dev/null)" ]] && return 0
    echo -n "Retrieving Federation Certificates..." >&2

    if ! wget -O $ESG_HOME/esg-truststore.ts --no-check-certificate https://github.com/ESGF/esgf-dist/raw/master/installer/certs/esg-truststore.ts; then
        echo "Could not fetch esg-truststore";
        return 1
    fi
    
    if ! wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar -O - -q | tar x -C $ESG_HOME; then
        #certificates tarred into esg_trusted_certificates. (if it breaks, let the user know why
        wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar
        echo "Could't update certs!" >&2
        return 1
    else
        #if here everythng went fine. Replace old cert with this ones    
        [[ -d $ESG_CERT_DIR ]] && rm -r $ESG_CERT_DIR || mkdir -p $(dirname $ESG_CERT_DIR)
        mv $ESG_HOME/esg_trusted_certificates $ESG_CERT_DIR
        touch $ESG_CERT_DIR
        echo "done!" >&2
    fi

}

# Retrieve ESG credentials
unset pass
get_credentials() {
    if check_java
    then
	use_java=1
    else	
	use_java=0
	echo "No suitable java for obtaining certificate - checking for myproxy-logon instead" >&2
	check_myproxy_logon || exit 1
    fi
    #get all certificates
    get_certificates

    if [[ -z "$(find $MYPROXY_GETCERT -type f -mtime -1 2>/dev/null)" ]]; then
        echo -n "(Downloading $MYPROXY_GETCERT... "
        mkdir -p $(dirname $MYPROXY_GETCERT)
        if wget -q --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/getcert.jar -O $MYPROXY_GETCERT;then
            echo 'done)'
            touch $MYPROXY_GETCERT
        else
            echo 'failed)'
        fi
    fi

    #if the user already defined one, use it
    if [[ -z $openId ]]; then
        #try to parse the last valid value if any
        [[ -f "$MYPROXY_STATUS" ]] && openId=$(awk -F= '/^OpenID/ {gsub("\\\\", ""); print $2}' $MYPROXY_STATUS)
        if [[ -z $openId ]]; then
            #no OpenID, we need to ask the user
            echo -n "Please give your OpenID (Example: https://myserver/example/username) ? "
        else
            #Allow the user to change it if desired
            echo -n "Please give your OpenID (hit ENTER to accept default: $openId)? "
        fi
        read -e
        [[ "$REPLY" ]] && openId="$REPLY"
    else
        ((verbose)) && echo "Using user defined OpenID $openId (to change use -o <open_id>)"
    fi

    if grep -q ceda.ac.uk <<<$openId; then
        username=${openId##*/}
        echo -n "Please give your username if different [$username]: "
        read -e
        [[ "$REPLY" ]] && username="$REPLY"
    fi
    


    if [ $use_java -eq 1 ]
    then
        local args=
        #get password
	[[ ! "$pass" ]] && read -sp "MyProxy Password? " pass
        [[ "$openId" ]] && args=$args" --oid $openId"
        [[ "$pass" ]] && args=$args" -P $pass"
        [[ "$username" ]] && args=$args" -l $username"
        
        echo -n $'\nRetrieving Credentials...' >&2
        if ! java $(proxy_to_java) -jar $MYPROXY_GETCERT $args --ca-directory $ESG_CERT_DIR --output $ESG_CREDENTIALS ; then        
            echo "Certificate could not be retrieved"
            exit 1
        fi
        echo "done!" >&2
    else
        args=`openid_to_myproxy_args $openId $username` || exit 1
        if ! myproxy-logon $args -b -o $ESG_CREDENTIALS
	then
            echo "Certificate could not be retrieved"
	    exit 1
        fi
	cp $HOME/.globus/certificates/* $ESG_CERT_DIR/	
    fi
}

openid_to_myproxy_args() {
  python - <<EOF || exit 1
import sys
import re
import xml.etree.ElementTree as ET
import urllib2
openid = "$1"
username = "$2" or re.sub(".*/", "", openid)
e = ET.parse(urllib2.urlopen(openid))
servs = [el for el in e.getiterator() if el.tag.endswith("Service")]
for serv in servs:
    servinfo = dict([(re.sub(".*}", "", c.tag), c.text)
                     for c in serv.getchildren()])
    try:
        if servinfo["Type"].endswith("myproxy-service"):
            m = re.match("socket://(.*):(.*)", servinfo["URI"])
            if m:
                host = m.group(1)
                port = m.group(2)
                print "-s %s -p %s -l %s" % (host, port, username)
                break
    except KeyError:
        continue
else:
    sys.stderr.write("myproxy service could not be found\n")
    sys.exit(1)
EOF
}

# check the certificate validity
check_cert() {
    if [[ ! -f "$ESG_CERT" || $force ]]; then
        #not there, just get it
        get_credentials
    elif which openssl &>/dev/null; then
        #check openssl and certificate
        if ! openssl x509 -checkend $CERT_EXPIRATION_WARNING -noout -in $ESG_CERT 2>/dev/null; then
            echo "The certificate expires in less than $((CERT_EXPIRATION_WARNING / 60 / 60)) hour(s). Renewing..."
            get_credentials
        else
            #ok, certificate is fine
            return 0
        fi
    fi
}

#
# Detect ESG credentials
#
find_credentials() {

    #is X509_USER_PROXY or $HOME/.esg/credential.pem
    if [[ -f "$ESG_CREDENTIALS" ]]; then
        # file found, proceed.
        ESG_CERT="$ESG_CREDENTIALS"
        ESG_KEY="$ESG_CREDENTIALS"
    elif [[ -f "$X509_USER_CERT" && -f "$X509_USER_KEY" ]]; then
        # second try, use these certificates.
        ESG_CERT="$X509_USER_CERT"
        ESG_KEY="$X509_USER_KEY"
    else
        # If credentials are not present, just point to where they should go 
        echo "No ESG Credentials found in $ESG_CREDENTIALS" >&2
            ESG_CERT="$ESG_CREDENTIALS"
            ESG_KEY="$ESG_CREDENTIALS"
            #they will be retrieved later one
    fi


    #chek openssl and certificate
    if (which openssl &>/dev/null); then
        if ( openssl version | grep 'OpenSSL 1\.0' ); then
            echo '** WARNING: ESGF Host certificate checking might not be compatible with OpenSSL 1.0+'
        fi
        check_cert || { (($?==1)); exit 1; }
    fi
    
    if [[ $CHECK_SERVER_CERT == "Yes" ]]; then
        [[ -d "$ESG_CERT_DIR" ]] || { echo "CA certs not found. Aborting."; exit 1; }
        PKI_WGET_OPTS="--ca-directory=$ESG_CERT_DIR"
    fi

    #some wget version complain if there's no file present
    [[ -f $COOKIE_JAR ]] || touch $COOKIE_JAR

    PKI_WGET_OPTS="$PKI_WGET_OPTS --certificate=$ESG_CERT --private-key=$ESG_KEY --save-cookies=$COOKIE_JAR --load-cookies=$COOKIE_JAR --ca-certificate=$ESG_CERT"

}

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

#Download data from node using cookies and not certificates.
download_http_sec()
{
  #The data to be downloaded.
  data=" $url"
  filename="$file"  

  #Wget args.
  if ((insecure)) 
  then
   wget_args=" --no-check-certificate --cookies=on  --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt " 
  else
   wget_args=" --ca-directory=$WGET_TRUSTED_CERTIFICATES --cookies=on --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt "  
  fi 

  if ((use_cookies_for_http_basic_auth_start)) || ((use_cookies_for_http_basic_auth)) 
  then
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
  fi
  
  if((force_TLSv1))
  then
   wget_args=" $wget_args"" --secure-protocol=TLSv1 "
  fi
  
  
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
    wget_args="$wget_args $ESGF_WGET_OPTS"
  fi  
  

  #use cookies for the next downloads
  use_cookies_for_http_basic_auth=1;
   
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "wget $wget_args $data\n"
  fi


  #Try to download the data. 
  command="wget $wget_args -O $filename $data"
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
      
  #Extract orp service from url ?
  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" == 1 )) && 
  if  echo "$http_resp" | grep -q "/esg-orp/"      
  then
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   orp_service=$(echo "$urls" | tr '\n' ' ' | cut -d' ' -f 2)


   #Use cookies for transaction with orp.
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
   
   #Download data using either http basic auth or http login form.
   if [[ "$openid_c" == */openid/  || "$openid_c" == */openid ]]
   then
    download_http_sec_open_id
   else
    download_http_sec_decide_service
   fi
  else  
   if    echo "$http_resp" | grep -q "401 Unauthorized"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || echo "$http_resp" | grep -q "Connection timed out."  \
      || echo "$http_resp" | grep -q "no-check-certificate"  \
      || (( $cmd_exit_status != 0 ))      
   then 
    echo "ERROR : http request to OpenID Relying Party service failed."
    failed=1
   fi
  fi
}


#Function that decides which implementaion of idp to use.
download_http_sec_decide_service()
{
  #find claimed id

  pos=$(echo "$openid_c" | egrep -o '/' | wc -l)
  username_c=$(echo "$openid_c"  | cut -d'/' -f "$(($pos + 1))")
  esgf_uri=$(echo "$openid_c" | egrep -o '/esgf-idp/openid/')

  host=$(echo "$openid_c"  | cut -d'/' -f 3)
  #test ceda first.

  if [[ -z "$esgf_uri" ]]
  then
   openid_c_tmp="https://""$host""/openid/"
  else
   openid_c_tmp="https://""$host""/esgf-idp/openid/" 
  fi

  command="wget "$openid_c_tmp" --no-check-certificate ${force_TLSv1:+--secure-protocol=TLSv1} -O-"
        
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
   command="$command $ESGF_WGET_OPTS"
  fi  
          
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "$command\n"
  fi
            

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
  

  if    echo "$http_resp" | grep -q "[application/xrds+xml]"  \
     && echo "$http_resp" | grep -q "200 OK"  \
     && (( cmd_exit_status == 0 ))       
  then
   openid_c=$openid_c_tmp
   download_http_sec_open_id
  else
   if [[ -z "$esgf_uri" ]]
   then
    echo "ERROR : HTTP request to OpenID Relying Party service failed."
    failed=1
   else
   download_http_sec_cl_id
   fi
  fi
}


download_http_sec_retry()
{
  echo -e "\nRetrying....\n"
  #Retry in case that last redirect did not work, this happens with older version of wget.
  command="wget $wget_args $data"
      
  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi   
   
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"

  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
   
  if    echo "$http_resp" | grep -q "401 Unauthorized"  \
     || echo "$http_resp" | grep -q "403: Forbidden"  \
     || echo "$http_resp" | grep -q "Connection timed out."  \
     || echo "$http_resp" | grep -q "no-check-certificate"  \
     || (( $cmd_exit_status != 0 ))      
  then 
   echo -e "\nERROR : Retry failed.\n"
   #rm "$filename"
   failed=1
  fi #if retry failed.
}

#Function for downloading data using the claimed id.
download_http_sec_cl_id()
{
  #Http request for sending openid to the orp service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\"  $wget_args -O- https://$orp_service/esg-orp/j_spring_openid_security_check.htm "

  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "wget $command\n"
  fi 
  
  
  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"

  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
    
  
  #Extract orp service from openid ?
  #Evaluate response.If redirected to idp service send the credentials.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( redirects == 2  )) && 
  if  echo "$http_resp" | grep -q "login.htm"  && (( cmd_exit_status == 0 ))   
  then 
  
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   idp_service=$(echo "$urls"  | tr '\n' ' ' | cut -d' ' -f 2) 
      
   command="wget --post-data  password=\"$password_c\" $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$idp_service/esgf-idp/idp/login.htm"
   

   #Debug message.
   if  ((debug))
   then
    echo -e "Executing:\n"
    echo -e "wget $command\n"
   fi 

   #Execution of command.
   http_resp=$(eval $command  2>&1)
   cmd_exit_status="$?"
      
   if ((debug))
   then
    echo -e "\nHTTP response:\n $http_resp\n"
   fi 
        
   #Evaluate response. 
   #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
   #(( "$redirects" != 5 )) \ 
   if    echo "$http_resp" | grep -q "text/html"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || (( cmd_exit_status != 0 ))        
   then 
    rm "$filename"
    download_http_sec_retry
   fi
 
  else
   echo "ERROR : HTTP request to OpenID Provider service failed."
   failed=1
  fi #if redirected to idp.  
}



download_http_sec_open_id()
{
  #Http request for sending openid to the orp web service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\" --header=\"esgf-idea-agent-type:basic_auth\" --http-user=\"$username_c\" --http-password=\"$password_c\"  $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$orp_service/esg-orp/j_spring_openid_security_check.htm "


  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi 

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 

  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" != 7 )) ||
  if   echo "$http_resp" | grep -q "text/html"  ||  (( $cmd_exit_status != 0 ))   
  then
   rm "$filename"
   download_http_sec_retry     
  fi #if error during http basic authentication. 
  
}


download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v} -c ${force_TLSv1:+--secure-protocol=TLSv1} $PKI_WGET_OPTS"
    
    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"
        
        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi
        
        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have. 
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count
        
        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                if ((use_http_sec))
                then
                 download_http_sec
                 if ((failed))
                 then
                  break
                 fi
                else
                 $wget -O "$file" $url || { failed=1; break; }  
                fi                
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi
                        
                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done
        
        if ((failed)); then
            echo "download failed"
            # most common failure is certificate expiration, so check this
            #if we have the pasword we can retrigger download
            ((!skip_security)) && [[ "$pass" ]] && check_cert
            unset failed
        fi
        
done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

http_basic_auth_func_info_message()
{
  echo  "********************************************************************************"
  echo  "*                                                                              *"
  echo  "* Note that new functionality to allow authentication without the need for     *"
  echo  "* certificates is available with this version of the wget script.  To enable,  *"
  echo  "* use the \"-H\" option and enter your OpenID and password when prompted:        *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -H [options...]                                     *"
  echo  "*                                                                              *"
  echo  "* For a full description of the available options use the help option:         *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -h                                                  *"
  echo  "*                                                                              *"
  echo  "********************************************************************************"
}

#
# MAIN
#

if ((!use_http_sec))
then 
 http_basic_auth_func_info_message
fi

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

((debug)) && cat<<EOF
** Debug info **
ESG_HOME=$ESG_HOME
ESG_CREDENTIALS=$ESG_CREDENTIALS
ESG_CERT_DIR=$ESG_CERT_DIR
** -- ** -- ** -- ** --

EOF


cat <<'EOF-MESSAGE'
Script created for 90 file(s)
(The count won't match if you manually edit this file!)



EOF-MESSAGE
sleep 1

check_os
((!skip_security)) && find_credentials

if ((use_http_sec))
then 
     
 if (( ! insecure))
 then 
  get_certificates
 fi

 #Cookies folder.
 COOKIES_FOLDER="$ESG_HOME/wget_cookies"
 
 if (( force ))
 then
  if [ -d $COOKIES_FOLDER ] 
  then
   rm -rf $COOKIES_FOLDER
  fi
 fi

 #Create cookies folder. 
 if [[ ! -d $COOKIES_FOLDER ]] 
 then
  mkdir $COOKIES_FOLDER
 fi
 
 if((! use_cookies_for_http_basic_auth_start))
 then

  #Read openid.
  if [[ ! -z "$openId" ]]
  then
   openid_c="$openId"
  elif ( (("$#" > 1)) || (("$#" == 1)) ) 
  then
   openid_c=$1
  else
   read -p    "Enter your openid : " openid_c
  fi
  
  
  #Read username.
  if [[ ! -z "$username_supplied" ]]
  then
   username_c="$username_supplied"
  elif (("$#" == 2))
  then
   username_c=$2
  elif [[ "$openid_c" == */openid/ || "$openid_c" == */openid ]]
  then
   read -p    "Enter username : " username_c
  fi
  
  #Read password.
  read -s -p "Enter password : " password_c
  echo -e "\n"

 fi #use cookies

fi #use_http_sec 


#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#clean the force parameter if here (at htis point we already have the certificate)
unset force

download

dedup_cache_


echo "done"
