#!/bin/bash
##############################################################################
# ESG Federation download script
#
# Template version: 1.2
# Generated by esg-dn1.nsc.liu.se - 2023/02/21 12:49:27
# Search URL: http://esg-dn1.nsc.liu.se/esg-search/wget/?distrib=false&dataset_id=CMIP6.RFMIP.EC-Earth-Consortium.EC-Earth3.piClim-control.r2i1p1f1.Amon.rsutcs.gr.v20211201|esg-dn2.nsc.liu.se
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############" 
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=1.3.2
CACHE_FILE=.$(basename $0).status
openId=
search_url='http://esg-dn1.nsc.liu.se/esg-search/wget/?distrib=false&dataset_id=CMIP6.RFMIP.EC-Earth-Consortium.EC-Earth3.piClim-control.r2i1p1f1.Amon.rsutcs.gr.v20211201|esg-dn2.nsc.liu.se'

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185001-185012.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185001-185012.nc' 'SHA256' '3c52011226e86d85e06b32b6093ccca66d83b98846d670c578c3475b29ee58b2'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185101-185112.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185101-185112.nc' 'SHA256' 'f47d50a32b1e37ba5bfe58d077563db8efdc4e08c9332cd51fead3efb66c5b3c'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185201-185212.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185201-185212.nc' 'SHA256' 'b7a9474406d819056457db52340a51e97a726f6f5cfe7915315725f7af3f7651'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185301-185312.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185301-185312.nc' 'SHA256' 'd9841d2eaa1759b9317cca3c0e87cdb4e5469759d0a6a7734f7d7f4988831146'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185401-185412.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185401-185412.nc' 'SHA256' 'd8987a2f86bf8dc28dcd290929f120dcb8186722bea2f24322e458d357533196'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185501-185512.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185501-185512.nc' 'SHA256' '6a1ffd23608f20259c799f973f7788a8546d7c9bf7daa78d18df73f376c93e0f'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185601-185612.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185601-185612.nc' 'SHA256' 'f62c156e59c28463707e5b35578e42aa2d146530d63f3b5a2b778e926f91e342'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185701-185712.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185701-185712.nc' 'SHA256' 'ea52ecdbe96f723375acf6090957a6a454957ab4b134ccfd545c59ee48d3df56'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185801-185812.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185801-185812.nc' 'SHA256' '26c67f3834c0ffd46960c8f2a5bdd2bff992d3f3d479b0c87b5e60c570732eb5'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185901-185912.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185901-185912.nc' 'SHA256' '0f746427fefe37e030b6e37f07804eb5a8d4e3893d6aa65932dd2f5700c5252d'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186001-186012.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186001-186012.nc' 'SHA256' 'b519ce3db24c04d64f7e070c363e5311d4c3c56190596065c5d726e0b998bd44'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186101-186112.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186101-186112.nc' 'SHA256' '300df375b5561bac23317ca2a2d5b0a8dbe56ca3da12affcdf15d480eb1f89e5'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186201-186212.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186201-186212.nc' 'SHA256' 'b270e5f3a2193ba33eefc1906c1193e637ee90077dba042b6972499409aa37ed'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186301-186312.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186301-186312.nc' 'SHA256' '5ac87a243ad672db3924eb6c6296c448da21436315261fadd0703389d9dcc721'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186401-186412.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186401-186412.nc' 'SHA256' 'b881de0b283ba4770563cfc2b9596cbe76d0c9c32f018180b23f5ba3a70b51e4'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186501-186512.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186501-186512.nc' 'SHA256' 'c4b01a425083eec0d576baa56b19204a0894536cad0fcd3a2352851de88044da'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186601-186612.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186601-186612.nc' 'SHA256' 'e2de4cdc16d15abbc42fa1cb9b1f4234b0ed89a51d593265f61a4285daeaf986'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186701-186712.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186701-186712.nc' 'SHA256' '0a9e7d16de0bdb05aa361fa17ec93fe4e3b54526c164e8221de36eda6ed8e048'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186801-186812.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186801-186812.nc' 'SHA256' 'f9de758373ecfcc315bebd9709b56c4496200f5f9143817a4d5b35ce6f7093d2'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186901-186912.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186901-186912.nc' 'SHA256' '3859d7f06244a08d59ac46d172daa2ea99f6eca67dd7dce8b5ba5c90b9609995'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187001-187012.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187001-187012.nc' 'SHA256' '299188fe1db1e9b12e3388902cdb808bb4d22b7d8dfe28aba7d6c42cb448c28d'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187101-187112.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187101-187112.nc' 'SHA256' 'e2e7bdce3cbe54980459b4647a17830be875bd98f7897a35be5eac6f834c695d'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187201-187212.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187201-187212.nc' 'SHA256' 'ee48db78bc35f516b80d1d004a0ecf3bf386f3b3eb1fbe0dab7f5241cddd9745'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187301-187312.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187301-187312.nc' 'SHA256' 'f28c8115de7ce896d16d9e211ec451fc916c1b02909c70e6bdb9de76df3f9f44'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187401-187412.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187401-187412.nc' 'SHA256' 'b4de38f2bd99425388e346d276e97af8a843d73eabbefda722032c25134e9432'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187501-187512.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187501-187512.nc' 'SHA256' '11420ec3dd76f5fda979c52eeb5e07dc6d4f5859c9baaae421c33691409c0d31'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187601-187612.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187601-187612.nc' 'SHA256' 'dcaa51facfe6c60e76147409973a817fefb97413d26e5666cf1e69f77bb9cca4'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187701-187712.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187701-187712.nc' 'SHA256' '2d1c86c9638525d8b4a7e1cd2309a0c100273ab811efd21d05af7fc6bf695533'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187801-187812.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187801-187812.nc' 'SHA256' '7aa9014a2d6c46137675043d17cbc2d842c67987dc2cd050cc0220d4e4851403'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187901-187912.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187901-187912.nc' 'SHA256' 'ae7aa0e5f7bfa1fe3fbefd43c679a9f05b8a4e3cc6af2326f19785b7dcce9413'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188001-188012.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188001-188012.nc' 'SHA256' 'ca0b76516d339de3d8fcc83f16e9f82453ccab3250d4bd9216b297e65de3896b'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188101-188112.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188101-188112.nc' 'SHA256' '2d8d5585f0c3db92ad7874d496235bf8d970b2d5af349a2fe9886bdd211b01dc'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188201-188212.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188201-188212.nc' 'SHA256' 'd6470e331df1a78564201afab057c19c296d027e02994913cffc00972ac34302'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188301-188312.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188301-188312.nc' 'SHA256' '391785ba2390af2807f2599175dd98e74d74992da7ec3656e9518d6f653d5152'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188401-188412.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188401-188412.nc' 'SHA256' '88f87084224149b53db909ff73062babfeb8ee00c583ce6207db206b34afdaf1'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188501-188512.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188501-188512.nc' 'SHA256' '4a4c4395a7f42d892358697ed98bbae2f0f6389539448c2df9d9594625231b42'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188601-188612.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188601-188612.nc' 'SHA256' '2b9368c82263f5ef898fac454e608b469141f2228ef57e22791bbbf267d437b6'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188701-188712.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188701-188712.nc' 'SHA256' 'a649c9d2ff5d5c14f204db8c60f95ca3806fe37fe6b3b791c19b9c0d17c86edb'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188801-188812.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188801-188812.nc' 'SHA256' 'b99c2fdf0fb2acccd19ecca05f51ccea50a6f7594b3b6abe02ab050975fd357b'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188901-188912.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188901-188912.nc' 'SHA256' '665e84d3c99b20b86735fdb8bccc1ccdaee4bad10f3bba9b999efd69cdca325d'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189001-189012.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189001-189012.nc' 'SHA256' 'dfed904f8da13c62a0cb1d0752fb078d518c649adb8aedafab8e23c267a6caa8'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189101-189112.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189101-189112.nc' 'SHA256' 'ede4fbaef051febb3afa5f772f98b9886c961ae6ab47896956de760bf0565035'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189201-189212.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189201-189212.nc' 'SHA256' '406cdb9a90fbafd4d4ae24b35a49e05e31e970acd417b3f53cfb9ca132b2950f'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189301-189312.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189301-189312.nc' 'SHA256' 'ea4d9c4d19e33bc745f54fda4d273cdf526bc73f994940c15e6e5615ec378a18'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189401-189412.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189401-189412.nc' 'SHA256' '0b345262d1780f83377c7519be44fcd27eed4bf1b2dc13e402fe138e5e48e702'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189501-189512.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189501-189512.nc' 'SHA256' '336601f66af6a0f597dba2f48f4f5c77aa45259c8d18fa6c18cd29ca0abc35b1'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189601-189612.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189601-189612.nc' 'SHA256' '06e26a823754b43f0740ae7f16b89927bfe6e03e9e8630260c6be818a66abe89'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189701-189712.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189701-189712.nc' 'SHA256' 'd1b49f4615965a519f16e13af885a8dd3063711d15f55760e81b69bc941a9ad7'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189801-189812.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189801-189812.nc' 'SHA256' '645cfc92e4c1996cdad6cb6d6cfbb995ba11e7af3eba5c2d30b3d73f3cfb18a4'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189901-189912.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189901-189912.nc' 'SHA256' '1f581fc4689122f124db0a9b7f6bf6b9eb7987b715c8bb5f608d8c51a96593ff'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190001-190012.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190001-190012.nc' 'SHA256' '64992b49eb76089a6969cfe777333a1dbb0d1f12888587b25b600064e1f0dcd1'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190101-190112.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190101-190112.nc' 'SHA256' '2983721d85a1ffd32db705fd0ca6bde7b9e19dd399e35e3bd07a49e9380e0be4'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190201-190212.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190201-190212.nc' 'SHA256' '5fea4d6499db58230e1572bd4f9c25b4bfba096c70251a130ff7e4a48c7bcb8f'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190301-190312.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190301-190312.nc' 'SHA256' 'b83852bcc79cee37b858e1117b0daa4af51327a20e480555576d93dd5e39c717'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190401-190412.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190401-190412.nc' 'SHA256' '36bb61f777e84bfd11b3641b845d41c9d7afb8abb52a6d14ab3efa7d66a9fcd2'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190501-190512.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190501-190512.nc' 'SHA256' '9feb63b3e591e6f80de220fa8bff9cf27590fab3cbd7d4cb2fbbd3a7c2e8a88a'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190601-190612.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190601-190612.nc' 'SHA256' '9f51188e5db821926c40040cb658c70983f5e832b83cc4855480d8a37459ec3b'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190701-190712.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190701-190712.nc' 'SHA256' '1a271dfa5a616893996eef1ac83075e8d37d8279ca1d0fa9400e02efa1642112'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190801-190812.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190801-190812.nc' 'SHA256' 'd942f8aa4d8d9ee85d5ec16821a2c486e554aa7772661321bea4320e82e3d6f1'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190901-190912.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190901-190912.nc' 'SHA256' 'd7d4b00e3591f18a21890aafa3f50b77927643cebb4c81a647af9a184a80d9f0'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191001-191012.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191001-191012.nc' 'SHA256' '9fa39b917c1fe0ab0ead4801e0d044c135e334a81c4151e6835f9e9a921c0751'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191101-191112.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191101-191112.nc' 'SHA256' '1db5486c0df3a2ff57ceae769722db239e85d2c34f1da4a11a72be895fa4a45e'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191201-191212.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191201-191212.nc' 'SHA256' '931485196525c8eaaf3278508b86788232d03f4b0b3590886701f4021c956795'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191301-191312.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191301-191312.nc' 'SHA256' '1f146cadee44f7f73cee095a4dc017fab81758e210b4e3856cec45b66cd015e7'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191401-191412.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191401-191412.nc' 'SHA256' '1a0f7df3b258086d30677b44250be086b90ad6d5461b5bf7bd567c02b886f756'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191501-191512.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191501-191512.nc' 'SHA256' '20cf2987743c7dde93fe8e4ce2f1f4f17d8ac33f86d9add829b0507c028d79af'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191601-191612.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191601-191612.nc' 'SHA256' '00e131aad10433c6a4c7743654fdc5fac71a5f72acd9e3030bc1c374abd30528'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191701-191712.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191701-191712.nc' 'SHA256' 'f9ecdf26c8a67ec283dd761074905a235fa75dc28e3ccd1f7381ae1addd88aed'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191801-191812.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191801-191812.nc' 'SHA256' 'f7bdd01c341e418064926cdfcdb3ab156ab475064728d4721e30b0eb727722f3'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191901-191912.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191901-191912.nc' 'SHA256' '195d548a17784f49f0e8bf42aa1d618573f1b35dfc56d3ed6f1f0f4c25aba845'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192001-192012.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192001-192012.nc' 'SHA256' 'd7699e6019b2c03d1ff306e5b00ded27cd9cccfe5c56d7b2ce22ebbbf087dcf8'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192101-192112.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192101-192112.nc' 'SHA256' '98c6c98a20fce3f816560b0f978bef9c2ccda2d3b11add815fb80b240f0072fe'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192201-192212.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192201-192212.nc' 'SHA256' 'be7d507232046fb31e27efbaa06dad89054ceb2156090eb9ac104ec138359923'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192301-192312.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192301-192312.nc' 'SHA256' '8421bf3e11a10cc46abf8e8aa4c8f39012852368325823bc0728fb1409d28f20'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192401-192412.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192401-192412.nc' 'SHA256' '5d609d7e5cbc4419d7a7e1d1a58fe134aeac4655a888dc3e9e4df2ca6cb29d9d'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192501-192512.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192501-192512.nc' 'SHA256' 'e777c2695a6d3207162823f50af8debcc09bc698e725f2d8e5ba5dd61090877c'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192601-192612.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192601-192612.nc' 'SHA256' '2914717d25f461f1c4dbdc49abe0a9970e44545936f22576076296ad03f6b14a'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192701-192712.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192701-192712.nc' 'SHA256' 'b67e2856e68f86624bef1169215402670479a1ce1bcd9e32b9f6472295529936'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192801-192812.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192801-192812.nc' 'SHA256' '332315bffd8276e1f608c3f5808fdaf793f83e67a196634057d636a731b5823d'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192901-192912.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192901-192912.nc' 'SHA256' 'b34ecd119388520b9cb9ff763012bcda8b081c51ce884170af671b1a409db115'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193001-193012.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193001-193012.nc' 'SHA256' 'b7916ce4feb589e65e0ad33909712461826a98a034e738adc1d7bfc309f2df06'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193101-193112.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193101-193112.nc' 'SHA256' '5fc35b4b00eeb3e07739e0280eaadc5155f62b6a0640d56bc02bea05b7e0e5f7'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193201-193212.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193201-193212.nc' 'SHA256' '6f5b42e5e28d21f9525f2e7cac5d7d366fbbb82be17f88ea4082f8dee0021a15'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193301-193312.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193301-193312.nc' 'SHA256' 'a780aca5ca15b291deb939c5b31ce296c9554959bc505026d2ee7122783e1f70'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193401-193412.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193401-193412.nc' 'SHA256' '40c5d9ae8f02dc4b3c16da16cd4a3b49e0c727f073616997695df69e090deea6'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193501-193512.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193501-193512.nc' 'SHA256' '62c55e84a845a03238d45d35c90d629959922b0cd9acf0f5a16f0abe6d573bd1'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193601-193612.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193601-193612.nc' 'SHA256' '1451df2ae28a0c56357b5c04ac0433910582055a4f6918de2c13f50ccb3fc773'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193701-193712.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193701-193712.nc' 'SHA256' '328d76a4acad2aea58a92982ad489648e6b0035ff5e336a650c8d4499ffb0c73'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193801-193812.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193801-193812.nc' 'SHA256' 'f6769ff591b5d65e6550dd937e823f4cfdca4cfafe2f73ef5d4ceeb5c748d198'
'rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193901-193912.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsutcs/gr/v20211201/rsutcs_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193901-193912.nc' 'SHA256' 'b4c653b257b80c4e53ec49c4520516bebf282832e4437fc52e9973f563511ba1'
EOF--dataset.file.url.chksum_type.chksum
)"

# ESG_HOME should point to the directory containing ESG credentials.
#   Default is $HOME/.esg
ESG_HOME=${ESG_HOME:-$HOME/.esg}
[[ -d $ESG_HOME ]] || mkdir -p $ESG_HOME

ESG_CREDENTIALS=${X509_USER_PROXY:-$ESG_HOME/credentials.pem}
ESG_CERT_DIR=${X509_CERT_DIR:-$ESG_HOME/certificates}
MYPROXY_STATUS=$HOME/.MyProxyLogon
COOKIE_JAR=$ESG_HOME/cookies
MYPROXY_GETCERT=$ESG_HOME/getcert.jar
CERT_EXPIRATION_WARNING=$((60 * 60 * 8))   #Eight hour (in seconds)

WGET_TRUSTED_CERTIFICATES=$ESG_HOME/certificates


# Configure checking of server SSL certificates.
#   Disabling server certificate checking can resolve problems with myproxy
#   servers being out of sync with datanodes.
CHECK_SERVER_CERT=${CHECK_SERVER_CERT:-Yes}

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags] [openid] [username]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
    echo "For more information check the website: http://esgf.org/wiki/ESGF_wget"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts ':c:pfF:o:w:isuUndvqhHI:T' OPT; do
    case $OPT in
        H) skip_security=1 && use_http_sec=1;; #       : Authenticate with OpenID (username,) and password, without the need for a certificate.
        T) force_TLSv1=1;;              #       : Forces wget to use TLSv1. 
        c) ESG_CREDENTIALS="$OPTARG";;  #<cert> : use this certificate for authentication.
        f) force=1;;                    #       : force certificate retrieval (defaults to only once per day); for certificate-less authentication (see -H option), this flag will force login and refresh cookies.
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        o) openId="$OPTARG";;           #<openid>: Provide OpenID instead of interactively asking for it.
        I) username_supplied="$OPTARG";;    #<user_id> : Explicitly set user ID.  By default, the user ID is extracted from the last component of the OpenID URL.  Use this flag to override this behaviour.                   
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        s) skip_security=1 && use_cookies_for_http_basic_auth_start=1;;            #       : completely skip security. It will only work if the accessed data is not secured at all. -- works only if the accessed data is unsecured or a certificate exists or cookies are saved (latter applies to -H option only).
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi


#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    new_wget="$(wget "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0      
fi


##############################################################################
check_java() {
    if ! type java >& /dev/null; then
        echo "Java could not be found." >&2
        return 1
    fi
    if java -version 2>&1|grep openjdk >/dev/null; then
        openjdk=1;
    else
        openjdk=0;
    fi
    jversion=($(jversion=$(java -version 2>&1 | awk '/version/ {gsub("\"","");print $3}'); echo ${jversion//./ }))
    mVer=${jversion[1]}
    if [ $openjdk -eq 1 ]; then
        mVer=${jversion[0]}
        if ((mVer<5)); then
            echo "Openjdk detected. Version 9+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    else
    
        if ((mVer<5)); then
            echo "Java version 1.5+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    fi
}

check_myproxy_logon() {
    if ! type myproxy-logon >& /dev/null; then
	echo "myproxy-logon could not be found." >&2
	return 1
    fi
    echo "myproxy-logon found" >&2
}

proxy_to_java() {
    local proxy_user proxy_pass proxy_server proxy_port
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$http_proxy)
    local JAVA_PROXY=
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyPort=$proxy_port"
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$https_proxy)
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyPort=$proxy_port"
    
    echo "$JAVA_PROXY"
}

# get certificates from github
get_certificates() {
    # don't if this was already done today
    [[ -z $force && "$(find $ESG_CERT_DIR -type d -mtime -1 2>/dev/null)" ]] && return 0
    echo -n "Retrieving Federation Certificates..." >&2

    if ! wget -O $ESG_HOME/esg-truststore.ts --no-check-certificate https://github.com/ESGF/esgf-dist/raw/master/installer/certs/esg-truststore.ts; then
        echo "Could not fetch esg-truststore";
        return 1
    fi
    
    if ! wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar -O - -q | tar x -C $ESG_HOME; then
        #certificates tarred into esg_trusted_certificates. (if it breaks, let the user know why
        wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar
        echo "Could't update certs!" >&2
        return 1
    else
        #if here everythng went fine. Replace old cert with this ones    
        [[ -d $ESG_CERT_DIR ]] && rm -r $ESG_CERT_DIR || mkdir -p $(dirname $ESG_CERT_DIR)
        mv $ESG_HOME/esg_trusted_certificates $ESG_CERT_DIR
        touch $ESG_CERT_DIR
        echo "done!" >&2
    fi

}

# Retrieve ESG credentials
unset pass
get_credentials() {
    if check_java
    then
	use_java=1
    else	
	use_java=0
	echo "No suitable java for obtaining certificate - checking for myproxy-logon instead" >&2
	check_myproxy_logon || exit 1
    fi
    #get all certificates
    get_certificates

    if [[ -z "$(find $MYPROXY_GETCERT -type f -mtime -1 2>/dev/null)" ]]; then
        echo -n "(Downloading $MYPROXY_GETCERT... "
        mkdir -p $(dirname $MYPROXY_GETCERT)
        if wget -q --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/getcert.jar -O $MYPROXY_GETCERT;then
            echo 'done)'
            touch $MYPROXY_GETCERT
        else
            echo 'failed)'
        fi
    fi

    #if the user already defined one, use it
    if [[ -z $openId ]]; then
        #try to parse the last valid value if any
        [[ -f "$MYPROXY_STATUS" ]] && openId=$(awk -F= '/^OpenID/ {gsub("\\\\", ""); print $2}' $MYPROXY_STATUS)
        if [[ -z $openId ]]; then
            #no OpenID, we need to ask the user
            echo -n "Please give your OpenID (Example: https://myserver/example/username) ? "
        else
            #Allow the user to change it if desired
            echo -n "Please give your OpenID (hit ENTER to accept default: $openId)? "
        fi
        read -e
        [[ "$REPLY" ]] && openId="$REPLY"
    else
        ((verbose)) && echo "Using user defined OpenID $openId (to change use -o <open_id>)"
    fi

    if grep -q ceda.ac.uk <<<$openId; then
        username=${openId##*/}
        echo -n "Please give your username if different [$username]: "
        read -e
        [[ "$REPLY" ]] && username="$REPLY"
    fi
    


    if [ $use_java -eq 1 ]
    then
        local args=
        #get password
	[[ ! "$pass" ]] && read -sp "MyProxy Password? " pass
        [[ "$openId" ]] && args=$args" --oid $openId"
        [[ "$pass" ]] && args=$args" -P $pass"
        [[ "$username" ]] && args=$args" -l $username"
        
        echo -n $'\nRetrieving Credentials...' >&2
        if ! java $(proxy_to_java) -jar $MYPROXY_GETCERT $args --ca-directory $ESG_CERT_DIR --output $ESG_CREDENTIALS ; then        
            echo "Certificate could not be retrieved"
            exit 1
        fi
        echo "done!" >&2
    else
        args=`openid_to_myproxy_args $openId $username` || exit 1
        if ! myproxy-logon $args -b -o $ESG_CREDENTIALS
	then
            echo "Certificate could not be retrieved"
	    exit 1
        fi
	cp $HOME/.globus/certificates/* $ESG_CERT_DIR/	
    fi
}

openid_to_myproxy_args() {
  python - <<EOF || exit 1
import sys
import re
import xml.etree.ElementTree as ET
import urllib2
openid = "$1"
username = "$2" or re.sub(".*/", "", openid)
e = ET.parse(urllib2.urlopen(openid))
servs = [el for el in e.getiterator() if el.tag.endswith("Service")]
for serv in servs:
    servinfo = dict([(re.sub(".*}", "", c.tag), c.text)
                     for c in serv.getchildren()])
    try:
        if servinfo["Type"].endswith("myproxy-service"):
            m = re.match("socket://(.*):(.*)", servinfo["URI"])
            if m:
                host = m.group(1)
                port = m.group(2)
                print "-s %s -p %s -l %s" % (host, port, username)
                break
    except KeyError:
        continue
else:
    sys.stderr.write("myproxy service could not be found\n")
    sys.exit(1)
EOF
}

# check the certificate validity
check_cert() {
    if [[ ! -f "$ESG_CERT" || $force ]]; then
        #not there, just get it
        get_credentials
    elif which openssl &>/dev/null; then
        #check openssl and certificate
        if ! openssl x509 -checkend $CERT_EXPIRATION_WARNING -noout -in $ESG_CERT 2>/dev/null; then
            echo "The certificate expires in less than $((CERT_EXPIRATION_WARNING / 60 / 60)) hour(s). Renewing..."
            get_credentials
        else
            #ok, certificate is fine
            return 0
        fi
    fi
}

#
# Detect ESG credentials
#
find_credentials() {

    #is X509_USER_PROXY or $HOME/.esg/credential.pem
    if [[ -f "$ESG_CREDENTIALS" ]]; then
        # file found, proceed.
        ESG_CERT="$ESG_CREDENTIALS"
        ESG_KEY="$ESG_CREDENTIALS"
    elif [[ -f "$X509_USER_CERT" && -f "$X509_USER_KEY" ]]; then
        # second try, use these certificates.
        ESG_CERT="$X509_USER_CERT"
        ESG_KEY="$X509_USER_KEY"
    else
        # If credentials are not present, just point to where they should go 
        echo "No ESG Credentials found in $ESG_CREDENTIALS" >&2
            ESG_CERT="$ESG_CREDENTIALS"
            ESG_KEY="$ESG_CREDENTIALS"
            #they will be retrieved later one
    fi


    #chek openssl and certificate
    if (which openssl &>/dev/null); then
        if ( openssl version | grep 'OpenSSL 1\.0' ); then
            echo '** WARNING: ESGF Host certificate checking might not be compatible with OpenSSL 1.0+'
        fi
        check_cert || { (($?==1)); exit 1; }
    fi
    
    if [[ $CHECK_SERVER_CERT == "Yes" ]]; then
        [[ -d "$ESG_CERT_DIR" ]] || { echo "CA certs not found. Aborting."; exit 1; }
        PKI_WGET_OPTS="--ca-directory=$ESG_CERT_DIR"
    fi

    #some wget version complain if there's no file present
    [[ -f $COOKIE_JAR ]] || touch $COOKIE_JAR

    PKI_WGET_OPTS="$PKI_WGET_OPTS --certificate=$ESG_CERT --private-key=$ESG_KEY --save-cookies=$COOKIE_JAR --load-cookies=$COOKIE_JAR --ca-certificate=$ESG_CERT"

}

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

#Download data from node using cookies and not certificates.
download_http_sec()
{
  #The data to be downloaded.
  data=" $url"
  filename="$file"  

  #Wget args.
  if ((insecure)) 
  then
   wget_args=" --no-check-certificate --cookies=on  --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt " 
  else
   wget_args=" --ca-directory=$WGET_TRUSTED_CERTIFICATES --cookies=on --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt "  
  fi 

  if ((use_cookies_for_http_basic_auth_start)) || ((use_cookies_for_http_basic_auth)) 
  then
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
  fi
  
  if((force_TLSv1))
  then
   wget_args=" $wget_args"" --secure-protocol=TLSv1 "
  fi
  
  
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
    wget_args="$wget_args $ESGF_WGET_OPTS"
  fi  
  

  #use cookies for the next downloads
  use_cookies_for_http_basic_auth=1;
   
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "wget $wget_args $data\n"
  fi


  #Try to download the data. 
  command="wget $wget_args -O $filename $data"
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
      
  #Extract orp service from url ?
  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" == 1 )) && 
  if  echo "$http_resp" | grep -q "/esg-orp/"      
  then
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   orp_service=$(echo "$urls" | tr '\n' ' ' | cut -d' ' -f 2)


   #Use cookies for transaction with orp.
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
   
   #Download data using either http basic auth or http login form.
   if [[ "$openid_c" == */openid/  || "$openid_c" == */openid ]]
   then
    download_http_sec_open_id
   else
    download_http_sec_decide_service
   fi
  else  
   if    echo "$http_resp" | grep -q "401 Unauthorized"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || echo "$http_resp" | grep -q "Connection timed out."  \
      || echo "$http_resp" | grep -q "no-check-certificate"  \
      || (( $cmd_exit_status != 0 ))      
   then 
    echo "ERROR : http request to OpenID Relying Party service failed."
    failed=1
   fi
  fi
}


#Function that decides which implementaion of idp to use.
download_http_sec_decide_service()
{
  #find claimed id

  pos=$(echo "$openid_c" | egrep -o '/' | wc -l)
  username_c=$(echo "$openid_c"  | cut -d'/' -f "$(($pos + 1))")
  esgf_uri=$(echo "$openid_c" | egrep -o '/esgf-idp/openid/')

  host=$(echo "$openid_c"  | cut -d'/' -f 3)
  #test ceda first.

  if [[ -z "$esgf_uri" ]]
  then
   openid_c_tmp="https://""$host""/openid/"
  else
   openid_c_tmp="https://""$host""/esgf-idp/openid/" 
  fi

  command="wget "$openid_c_tmp" --no-check-certificate ${force_TLSv1:+--secure-protocol=TLSv1} -O-"
        
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
   command="$command $ESGF_WGET_OPTS"
  fi  
          
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "$command\n"
  fi
            

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
  

  if    echo "$http_resp" | grep -q "[application/xrds+xml]"  \
     && echo "$http_resp" | grep -q "200 OK"  \
     && (( cmd_exit_status == 0 ))       
  then
   openid_c=$openid_c_tmp
   download_http_sec_open_id
  else
   if [[ -z "$esgf_uri" ]]
   then
    echo "ERROR : HTTP request to OpenID Relying Party service failed."
    failed=1
   else
   download_http_sec_cl_id
   fi
  fi
}


download_http_sec_retry()
{
  echo -e "\nRetrying....\n"
  #Retry in case that last redirect did not work, this happens with older version of wget.
  command="wget $wget_args $data"
      
  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi   
   
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"

  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
   
  if    echo "$http_resp" | grep -q "401 Unauthorized"  \
     || echo "$http_resp" | grep -q "403: Forbidden"  \
     || echo "$http_resp" | grep -q "Connection timed out."  \
     || echo "$http_resp" | grep -q "no-check-certificate"  \
     || (( $cmd_exit_status != 0 ))      
  then 
   echo -e "\nERROR : Retry failed.\n"
   #rm "$filename"
   failed=1
  fi #if retry failed.
}

#Function for downloading data using the claimed id.
download_http_sec_cl_id()
{
  #Http request for sending openid to the orp service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\"  $wget_args -O- https://$orp_service/esg-orp/j_spring_openid_security_check.htm "

  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "wget $command\n"
  fi 
  
  
  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"

  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
    
  
  #Extract orp service from openid ?
  #Evaluate response.If redirected to idp service send the credentials.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( redirects == 2  )) && 
  if  echo "$http_resp" | grep -q "login.htm"  && (( cmd_exit_status == 0 ))   
  then 
  
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   idp_service=$(echo "$urls"  | tr '\n' ' ' | cut -d' ' -f 2) 
      
   command="wget --post-data  password=\"$password_c\" $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$idp_service/esgf-idp/idp/login.htm"
   

   #Debug message.
   if  ((debug))
   then
    echo -e "Executing:\n"
    echo -e "wget $command\n"
   fi 

   #Execution of command.
   http_resp=$(eval $command  2>&1)
   cmd_exit_status="$?"
      
   if ((debug))
   then
    echo -e "\nHTTP response:\n $http_resp\n"
   fi 
        
   #Evaluate response. 
   #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
   #(( "$redirects" != 5 )) \ 
   if    echo "$http_resp" | grep -q "text/html"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || (( cmd_exit_status != 0 ))        
   then 
    rm "$filename"
    download_http_sec_retry
   fi
 
  else
   echo "ERROR : HTTP request to OpenID Provider service failed."
   failed=1
  fi #if redirected to idp.  
}



download_http_sec_open_id()
{
  #Http request for sending openid to the orp web service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\" --header=\"esgf-idea-agent-type:basic_auth\" --http-user=\"$username_c\" --http-password=\"$password_c\"  $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$orp_service/esg-orp/j_spring_openid_security_check.htm "


  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi 

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 

  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" != 7 )) ||
  if   echo "$http_resp" | grep -q "text/html"  ||  (( $cmd_exit_status != 0 ))   
  then
   rm "$filename"
   download_http_sec_retry     
  fi #if error during http basic authentication. 
  
}


download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v} -c ${force_TLSv1:+--secure-protocol=TLSv1} $PKI_WGET_OPTS"
    
    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"
        
        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi
        
        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have. 
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count
        
        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                if ((use_http_sec))
                then
                 download_http_sec
                 if ((failed))
                 then
                  break
                 fi
                else
                 $wget -O "$file" $url || { failed=1; break; }  
                fi                
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi
                        
                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done
        
        if ((failed)); then
            echo "download failed"
            # most common failure is certificate expiration, so check this
            #if we have the pasword we can retrigger download
            ((!skip_security)) && [[ "$pass" ]] && check_cert
            unset failed
        fi
        
done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

http_basic_auth_func_info_message()
{
  echo  "********************************************************************************"
  echo  "*                                                                              *"
  echo  "* Note that new functionality to allow authentication without the need for     *"
  echo  "* certificates is available with this version of the wget script.  To enable,  *"
  echo  "* use the \"-H\" option and enter your OpenID and password when prompted:        *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -H [options...]                                     *"
  echo  "*                                                                              *"
  echo  "* For a full description of the available options use the help option:         *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -h                                                  *"
  echo  "*                                                                              *"
  echo  "********************************************************************************"
}

#
# MAIN
#

if ((!use_http_sec))
then 
 http_basic_auth_func_info_message
fi

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

((debug)) && cat<<EOF
** Debug info **
ESG_HOME=$ESG_HOME
ESG_CREDENTIALS=$ESG_CREDENTIALS
ESG_CERT_DIR=$ESG_CERT_DIR
** -- ** -- ** -- ** --

EOF


cat <<'EOF-MESSAGE'
Script created for 90 file(s)
(The count won't match if you manually edit this file!)



EOF-MESSAGE
sleep 1

check_os
((!skip_security)) && find_credentials

if ((use_http_sec))
then 
     
 if (( ! insecure))
 then 
  get_certificates
 fi

 #Cookies folder.
 COOKIES_FOLDER="$ESG_HOME/wget_cookies"
 
 if (( force ))
 then
  if [ -d $COOKIES_FOLDER ] 
  then
   rm -rf $COOKIES_FOLDER
  fi
 fi

 #Create cookies folder. 
 if [[ ! -d $COOKIES_FOLDER ]] 
 then
  mkdir $COOKIES_FOLDER
 fi
 
 if((! use_cookies_for_http_basic_auth_start))
 then

  #Read openid.
  if [[ ! -z "$openId" ]]
  then
   openid_c="$openId"
  elif ( (("$#" > 1)) || (("$#" == 1)) ) 
  then
   openid_c=$1
  else
   read -p    "Enter your openid : " openid_c
  fi
  
  
  #Read username.
  if [[ ! -z "$username_supplied" ]]
  then
   username_c="$username_supplied"
  elif (("$#" == 2))
  then
   username_c=$2
  elif [[ "$openid_c" == */openid/ || "$openid_c" == */openid ]]
  then
   read -p    "Enter username : " username_c
  fi
  
  #Read password.
  read -s -p "Enter password : " password_c
  echo -e "\n"

 fi #use cookies

fi #use_http_sec 


#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#clean the force parameter if here (at htis point we already have the certificate)
unset force

download

dedup_cache_


echo "done"
