#!/bin/bash
##############################################################################
# ESG Federation download script
#
# Template version: 1.2
# Generated by esg-dn1.nsc.liu.se - 2023/02/21 12:50:03
# Search URL: http://esg-dn1.nsc.liu.se/esg-search/wget/?distrib=false&dataset_id=CMIP6.RFMIP.EC-Earth-Consortium.EC-Earth3.piClim-control.r2i1p1f1.Amon.rsds.gr.v20211201|esg-dn2.nsc.liu.se
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############" 
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=1.3.2
CACHE_FILE=.$(basename $0).status
openId=
search_url='http://esg-dn1.nsc.liu.se/esg-search/wget/?distrib=false&dataset_id=CMIP6.RFMIP.EC-Earth-Consortium.EC-Earth3.piClim-control.r2i1p1f1.Amon.rsds.gr.v20211201|esg-dn2.nsc.liu.se'

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185001-185012.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185001-185012.nc' 'SHA256' '89a86646a04509b8bda1e6756e63dc2552ccfa2d35dd0a8480e1d9c54fe59998'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185101-185112.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185101-185112.nc' 'SHA256' 'caf79b2b50d911b7478f8dff9177110817bc4546660bbbbe9aa138eaddacf8fc'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185201-185212.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185201-185212.nc' 'SHA256' '09523c0712e4ec1e476e2bc60ba68bf24718b770e0129f55c50cb814800cf914'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185301-185312.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185301-185312.nc' 'SHA256' '24cb1c381525e8a1dd93b353da0c463104b2d18a5b5821fe5df6d6b7d6bbd8bc'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185401-185412.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185401-185412.nc' 'SHA256' 'a6c4a3fc932d10618eaaf4cc6132d80527a61624379799ec14f9ca6bf36db5a8'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185501-185512.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185501-185512.nc' 'SHA256' 'bd516206a926dcb495712a5fe1ddfa88c88aaaa05c5ba0effc2aba1cdef0ae51'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185601-185612.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185601-185612.nc' 'SHA256' '298b12a43f2c24681db302780026b9d0f575f9b57c1ff7a2ac268b9c7cfb4785'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185701-185712.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185701-185712.nc' 'SHA256' '4a7ceae7154bf7a4b02a6a70d9af65e91a9df3bfeb574bb7cf7346df19c8ee19'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185801-185812.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185801-185812.nc' 'SHA256' '03c36c5f2a1d57a6da2b213afcc443fec22fc938455c9e1a40d72ecb1d0d34b2'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185901-185912.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185901-185912.nc' 'SHA256' '6f9d010e40e1545e9bcbfb51fe86a118d6431a9d9caf722987ff9a829f7c0927'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186001-186012.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186001-186012.nc' 'SHA256' '66916a5062eecc96245378f02822fbfc896b63490a09b2e8185e2bd9b29ec2b9'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186101-186112.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186101-186112.nc' 'SHA256' 'ee22e6c62f5cb12a00c065a4d6f2d74f4921b95bf5b431860eda8354631d134a'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186201-186212.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186201-186212.nc' 'SHA256' 'ed80a77c77707bd5832a8d874aba0827cf018e971fd12db9a550d82db06efbb0'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186301-186312.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186301-186312.nc' 'SHA256' 'fca9b4632e1af54dc51be5c29c2461830c4ce02c77ae95648a3be193fb563f1e'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186401-186412.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186401-186412.nc' 'SHA256' '460840d47b8a0765693ab2631671504f9f2ba714516c6cdb6b859573059310c6'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186501-186512.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186501-186512.nc' 'SHA256' 'a0743a85d65a9a2b43b62c77b1a2af9219f476b64ee75422b694c0b368dd3623'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186601-186612.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186601-186612.nc' 'SHA256' 'a0b973b98fbb98621ee3e23b058a7d8316494d7fb6ab55f54ad010bfc4d54281'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186701-186712.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186701-186712.nc' 'SHA256' '6f124405201bd3930e48b830b824fe8a0188ef92135a5596ffb2fbc5b25cd2ce'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186801-186812.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186801-186812.nc' 'SHA256' '71a81307855e1af938834a02cec87cdb9cf3c2832f170a0967a4a1853b3ee917'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186901-186912.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186901-186912.nc' 'SHA256' '013154252ff6e0684729698b22f3d6fde7bd6ec43537bfd70356d0bccb4f7d19'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187001-187012.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187001-187012.nc' 'SHA256' '6079d8d0f3d009a0bfb493d6445ec8930c9aff906e96ed2d1afebe3435b4798b'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187101-187112.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187101-187112.nc' 'SHA256' '00c2d7f2cab9308e4fc175c13e93ebb8a5da17229e97e347bf792aca65326054'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187201-187212.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187201-187212.nc' 'SHA256' 'f76d974226cdf10f4f281f74f80b572424ea7350892e859fc509ef384763fc19'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187301-187312.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187301-187312.nc' 'SHA256' '617227a04d00e267bb15f2d7c3a6a775a7025d42c55c9022febb420b19b9daf3'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187401-187412.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187401-187412.nc' 'SHA256' 'b589daef5e07cb7142384452f326d463d53d3b3a3cf41f6a25d9192b32af287b'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187501-187512.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187501-187512.nc' 'SHA256' 'fbd00390510aba6dee97e19b575a1dd5c3c75da3cd65b825f9125b9032ae3c2f'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187601-187612.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187601-187612.nc' 'SHA256' '684266db969da43b3964c916810d293f58362cbcd77766b78ebc6b0f1e37856d'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187701-187712.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187701-187712.nc' 'SHA256' '0c2d4d2ea8993628f3847374535d60e56da99ee90909d2472b61f6ed3ea57240'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187801-187812.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187801-187812.nc' 'SHA256' '4eaf37e366e055d29e045cfc6664feeef7763d97e0a6d83c75763fd749a7d1aa'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187901-187912.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187901-187912.nc' 'SHA256' '26e5484f7abd3175333170ff972353b35bb25e93ec620ad0fa41e3a29f6903e7'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188001-188012.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188001-188012.nc' 'SHA256' '79331f76e3548d1f70f3d4b038650ff2563959e8c9c31682413b142c07ac7ce5'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188101-188112.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188101-188112.nc' 'SHA256' '94570eff2a2fdf936329defd82fc1d77be88a177709938f6726080891f1029f4'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188201-188212.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188201-188212.nc' 'SHA256' 'a9be96d43c3c6bffbb7e7badcd63358382d57a54ff3b9fdf1b0adf916236630d'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188301-188312.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188301-188312.nc' 'SHA256' '3daac2e944ea76ddb0dc93c5a86ca02b72d2f24a6cd26a827fea37999733659d'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188401-188412.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188401-188412.nc' 'SHA256' '020da03629cf0fc105982bb0c2bebc09a70594dea8ca80cca7271ba58c763a6d'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188501-188512.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188501-188512.nc' 'SHA256' '3cbebc7eec1692efc62cbdb81399feb0e48b5bae2de6934a28e2ceeb538ca7e6'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188601-188612.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188601-188612.nc' 'SHA256' '4beb5b9554b76c5db7fd8c4e3b51aebfd2133f4aba24c733ff475ab267afeba6'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188701-188712.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188701-188712.nc' 'SHA256' '21bf1e15f11b39ae2b9bee3476fbde461f1b087eb79c80a948293dfa236acc34'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188801-188812.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188801-188812.nc' 'SHA256' '7a87975fbbbbc55e5085ea6719c6005e1a13e741aad98586d004175ad40ef664'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188901-188912.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188901-188912.nc' 'SHA256' 'bfee82c7a2922047d105f7536cfb00db1300eaf759f504837e581c1ff37fcbad'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189001-189012.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189001-189012.nc' 'SHA256' '91bb45217587036ccd735782cbc95bd4f8294bf0c5af0beb01adc211382b8bbb'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189101-189112.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189101-189112.nc' 'SHA256' '522219ef9aab7ae43499e3a3cc67c126a87eefeaeefdc48ae7b18b7b713a7d63'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189201-189212.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189201-189212.nc' 'SHA256' '35ab80ca83e793529e4e1e51c9d13d1e7aa09ec4ca1b93368f345672717b349d'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189301-189312.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189301-189312.nc' 'SHA256' 'b626d0e973c78e890f0c1fb3cf7a082b4858bad29b9bacc3bc08e143c6618cda'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189401-189412.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189401-189412.nc' 'SHA256' '09db63f3a73c275999783ab0a633cf2c3fb9f93ae8b84d2831443cb890a0ca31'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189501-189512.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189501-189512.nc' 'SHA256' '6b99b839310af31f36ef8cabfa6e2ae800e3c82862d9d259de6b350817040b45'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189601-189612.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189601-189612.nc' 'SHA256' '99eea0b327c892f76d2cceff937adc87a91a4b3f2d45520de5837c411dd94961'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189701-189712.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189701-189712.nc' 'SHA256' '11d6c0725d0054176aceb27f9e82ee86b57fc0a363852f3f03b9942727c9625c'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189801-189812.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189801-189812.nc' 'SHA256' '5c25890d1c445a5158e8715e4ab181a424ac137f4fd004ff31125c4a03d2fdfa'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189901-189912.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189901-189912.nc' 'SHA256' '64d89fb033cc7c5d52f5b0ea4663bccc50f535d9fb7992e2e89fb0ca2bc923a1'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190001-190012.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190001-190012.nc' 'SHA256' 'ac92de3c9df649d405cb0a13f80e97016a1e94b83095e0b7b4bb1dc012c717cf'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190101-190112.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190101-190112.nc' 'SHA256' '6e7ecb38acfed69d7ee4e942b1aed98504e1ec88615f7e3e3ca1cde1c134d20b'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190201-190212.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190201-190212.nc' 'SHA256' '4402a14b7f35cc27911fb50f05a17fb7157990571fcebb212c489a8a97a09e84'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190301-190312.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190301-190312.nc' 'SHA256' '487721bbb94f2f091553625b4db4e2b28b599cf48804a8d75ae7e1d048a5af81'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190401-190412.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190401-190412.nc' 'SHA256' '4a1a2c6071f55f5f22fdc9dae28fa4bfaf5d9da4f404497ed59c5cd569328b15'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190501-190512.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190501-190512.nc' 'SHA256' '8fefb5ab54b07ce65b57dbe7ddac0e29d48173da3ad38acdc841f1c778980405'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190601-190612.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190601-190612.nc' 'SHA256' '66e9f975e6dc9f3456c45621b4e07ee252d37651f4b5c048d812ef72392e1b3e'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190701-190712.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190701-190712.nc' 'SHA256' '9ddf502f265dff0a8e5caed7cde06b70f5271e3e034d617b5f44cba16e5dd97f'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190801-190812.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190801-190812.nc' 'SHA256' 'b0e446a811fda7fd2078eb6ff13acd9054d9a36e90785f01b74abcfd0e0adb48'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190901-190912.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190901-190912.nc' 'SHA256' 'acc054771110b7aca4038d5cc8327b85c42a9ecf389ad71225ead2d370df995d'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191001-191012.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191001-191012.nc' 'SHA256' 'b6b992f34a68d5f59fe13e8f039fbdbf5aa98375b54563f6d471fddcfcc7a101'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191101-191112.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191101-191112.nc' 'SHA256' '4568e2ba99538c38361f9e2f7a3eca79427a1811136bce9dbddd39871997acae'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191201-191212.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191201-191212.nc' 'SHA256' 'a54fd1545691fca44e4dc3d7c8342fef4b24db12c7f8b598a6300b0c70a226c6'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191301-191312.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191301-191312.nc' 'SHA256' '5585f7b3e4eb05eb58995c4cd99e98f5ab87cc564edb922ac13077ec866f50f2'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191401-191412.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191401-191412.nc' 'SHA256' '030b712267e729bc565db24cc64be183630ebd1570ea6693d9fa82fb54e260af'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191501-191512.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191501-191512.nc' 'SHA256' '079860209d11f4fba788e47b5f7af958b5aed3d438aa684ad2e4cd58cc28a9e8'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191601-191612.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191601-191612.nc' 'SHA256' '35fbfd90a2f6b19eed63c77993d827e12a87446384d32c174539bb710024ccd3'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191701-191712.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191701-191712.nc' 'SHA256' 'df4d9fd7a5f411a1120f9b5ee4ef590b6af9bf5b145b3b7205bff34e9e022fc7'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191801-191812.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191801-191812.nc' 'SHA256' 'eec50e1098ac76150f898448e64fa629ac286feb6edaf9eee7ee7a2ab9aaea2c'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191901-191912.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191901-191912.nc' 'SHA256' 'eaabfbee2fafe6acd10968f75014548fb36d58dfe12e22f72adf61f756573bac'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192001-192012.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192001-192012.nc' 'SHA256' 'ae0918fd0200984f259799d25b8469794a32b03d4088c149a73b1e6379d70674'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192101-192112.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192101-192112.nc' 'SHA256' '30cbf7d4ccd5f09395e001bbc4455540bfdc26ff777b52e0139eb72cab999f31'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192201-192212.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192201-192212.nc' 'SHA256' '64484e052cb2e85f174e21311161e9f301704067ec03f4e58719e942f0c7570b'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192301-192312.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192301-192312.nc' 'SHA256' 'e0dc5effe43aca9f948a153160104ad882b965d5b4796e2fea6e401d02904e7e'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192401-192412.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192401-192412.nc' 'SHA256' 'd27f244e4b78c4ddc1a86c1c6f7e44dc3049cf3fe4058a707ee8782b31b5e95d'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192501-192512.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192501-192512.nc' 'SHA256' '05f904e52a743deaae7388ddf605eabc7a772b8a92b604d03365755b9db95ab5'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192601-192612.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192601-192612.nc' 'SHA256' '8354d0143b8b12805f8a7ed343295ce6382a0d75a206931985ea8223e9f1ede5'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192701-192712.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192701-192712.nc' 'SHA256' '970dde8b28fcb1d93310d97356b4ebd3456f46323e2b9bd7fe523078d82cd0dd'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192801-192812.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192801-192812.nc' 'SHA256' '3855085049f59b2c2170485381aabd693155d167f9e06a5e558806bc75bad198'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192901-192912.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192901-192912.nc' 'SHA256' '5283bc1f113a43a1df092c8cdca14b5b35737ea6d67d85b34415459912892cd5'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193001-193012.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193001-193012.nc' 'SHA256' '1d76af15415f22ed28851b3f898712aaed138585d80afbf14a09a48ca435600e'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193101-193112.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193101-193112.nc' 'SHA256' '4a34d2f4c5aa1217b2e67b746669d1b7c6e2da8d7071d603af8fa9e2a690e411'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193201-193212.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193201-193212.nc' 'SHA256' 'eff6e1ee027fc64fd978393f8a951915c7494558e433718523955d1950e4590d'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193301-193312.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193301-193312.nc' 'SHA256' 'e5136b180064b73ed0c1e1f7e2b9d22b1927761b514c1a243e700055dec5bfe3'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193401-193412.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193401-193412.nc' 'SHA256' '593515979ca5e57c3e3d2b57a7f0beaa1827976ed0358751c605a3c182cafc65'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193501-193512.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193501-193512.nc' 'SHA256' '70f5bbf8b4611f6bbac2a69c3175b40eed4d38ccd83de4de147f8ae79366342c'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193601-193612.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193601-193612.nc' 'SHA256' '06ca52bdc5bf3c3b5084e91e05e2c546cc329339cb36061caaa7f6a66d63f928'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193701-193712.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193701-193712.nc' 'SHA256' '7552cceeea448a70053026ed81a239377afd4bb659e10b7b0333613cd94e0b3f'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193801-193812.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193801-193812.nc' 'SHA256' '4294dd92ef6031e3c1a6c084b3e81ab7818757ef2a3a48a671f2bc94d7b3a486'
'rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193901-193912.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/rsds/gr/v20211201/rsds_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193901-193912.nc' 'SHA256' '1cba891d631dc1b4586da3ae626785a739888df3e450d691ab3144e190ffd81d'
EOF--dataset.file.url.chksum_type.chksum
)"

# ESG_HOME should point to the directory containing ESG credentials.
#   Default is $HOME/.esg
ESG_HOME=${ESG_HOME:-$HOME/.esg}
[[ -d $ESG_HOME ]] || mkdir -p $ESG_HOME

ESG_CREDENTIALS=${X509_USER_PROXY:-$ESG_HOME/credentials.pem}
ESG_CERT_DIR=${X509_CERT_DIR:-$ESG_HOME/certificates}
MYPROXY_STATUS=$HOME/.MyProxyLogon
COOKIE_JAR=$ESG_HOME/cookies
MYPROXY_GETCERT=$ESG_HOME/getcert.jar
CERT_EXPIRATION_WARNING=$((60 * 60 * 8))   #Eight hour (in seconds)

WGET_TRUSTED_CERTIFICATES=$ESG_HOME/certificates


# Configure checking of server SSL certificates.
#   Disabling server certificate checking can resolve problems with myproxy
#   servers being out of sync with datanodes.
CHECK_SERVER_CERT=${CHECK_SERVER_CERT:-Yes}

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags] [openid] [username]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
    echo "For more information check the website: http://esgf.org/wiki/ESGF_wget"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts ':c:pfF:o:w:isuUndvqhHI:T' OPT; do
    case $OPT in
        H) skip_security=1 && use_http_sec=1;; #       : Authenticate with OpenID (username,) and password, without the need for a certificate.
        T) force_TLSv1=1;;              #       : Forces wget to use TLSv1. 
        c) ESG_CREDENTIALS="$OPTARG";;  #<cert> : use this certificate for authentication.
        f) force=1;;                    #       : force certificate retrieval (defaults to only once per day); for certificate-less authentication (see -H option), this flag will force login and refresh cookies.
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        o) openId="$OPTARG";;           #<openid>: Provide OpenID instead of interactively asking for it.
        I) username_supplied="$OPTARG";;    #<user_id> : Explicitly set user ID.  By default, the user ID is extracted from the last component of the OpenID URL.  Use this flag to override this behaviour.                   
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        s) skip_security=1 && use_cookies_for_http_basic_auth_start=1;;            #       : completely skip security. It will only work if the accessed data is not secured at all. -- works only if the accessed data is unsecured or a certificate exists or cookies are saved (latter applies to -H option only).
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi


#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    new_wget="$(wget "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0      
fi


##############################################################################
check_java() {
    if ! type java >& /dev/null; then
        echo "Java could not be found." >&2
        return 1
    fi
    if java -version 2>&1|grep openjdk >/dev/null; then
        openjdk=1;
    else
        openjdk=0;
    fi
    jversion=($(jversion=$(java -version 2>&1 | awk '/version/ {gsub("\"","");print $3}'); echo ${jversion//./ }))
    mVer=${jversion[1]}
    if [ $openjdk -eq 1 ]; then
        mVer=${jversion[0]}
        if ((mVer<5)); then
            echo "Openjdk detected. Version 9+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    else
    
        if ((mVer<5)); then
            echo "Java version 1.5+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    fi
}

check_myproxy_logon() {
    if ! type myproxy-logon >& /dev/null; then
	echo "myproxy-logon could not be found." >&2
	return 1
    fi
    echo "myproxy-logon found" >&2
}

proxy_to_java() {
    local proxy_user proxy_pass proxy_server proxy_port
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$http_proxy)
    local JAVA_PROXY=
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyPort=$proxy_port"
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$https_proxy)
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyPort=$proxy_port"
    
    echo "$JAVA_PROXY"
}

# get certificates from github
get_certificates() {
    # don't if this was already done today
    [[ -z $force && "$(find $ESG_CERT_DIR -type d -mtime -1 2>/dev/null)" ]] && return 0
    echo -n "Retrieving Federation Certificates..." >&2

    if ! wget -O $ESG_HOME/esg-truststore.ts --no-check-certificate https://github.com/ESGF/esgf-dist/raw/master/installer/certs/esg-truststore.ts; then
        echo "Could not fetch esg-truststore";
        return 1
    fi
    
    if ! wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar -O - -q | tar x -C $ESG_HOME; then
        #certificates tarred into esg_trusted_certificates. (if it breaks, let the user know why
        wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar
        echo "Could't update certs!" >&2
        return 1
    else
        #if here everythng went fine. Replace old cert with this ones    
        [[ -d $ESG_CERT_DIR ]] && rm -r $ESG_CERT_DIR || mkdir -p $(dirname $ESG_CERT_DIR)
        mv $ESG_HOME/esg_trusted_certificates $ESG_CERT_DIR
        touch $ESG_CERT_DIR
        echo "done!" >&2
    fi

}

# Retrieve ESG credentials
unset pass
get_credentials() {
    if check_java
    then
	use_java=1
    else	
	use_java=0
	echo "No suitable java for obtaining certificate - checking for myproxy-logon instead" >&2
	check_myproxy_logon || exit 1
    fi
    #get all certificates
    get_certificates

    if [[ -z "$(find $MYPROXY_GETCERT -type f -mtime -1 2>/dev/null)" ]]; then
        echo -n "(Downloading $MYPROXY_GETCERT... "
        mkdir -p $(dirname $MYPROXY_GETCERT)
        if wget -q --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/getcert.jar -O $MYPROXY_GETCERT;then
            echo 'done)'
            touch $MYPROXY_GETCERT
        else
            echo 'failed)'
        fi
    fi

    #if the user already defined one, use it
    if [[ -z $openId ]]; then
        #try to parse the last valid value if any
        [[ -f "$MYPROXY_STATUS" ]] && openId=$(awk -F= '/^OpenID/ {gsub("\\\\", ""); print $2}' $MYPROXY_STATUS)
        if [[ -z $openId ]]; then
            #no OpenID, we need to ask the user
            echo -n "Please give your OpenID (Example: https://myserver/example/username) ? "
        else
            #Allow the user to change it if desired
            echo -n "Please give your OpenID (hit ENTER to accept default: $openId)? "
        fi
        read -e
        [[ "$REPLY" ]] && openId="$REPLY"
    else
        ((verbose)) && echo "Using user defined OpenID $openId (to change use -o <open_id>)"
    fi

    if grep -q ceda.ac.uk <<<$openId; then
        username=${openId##*/}
        echo -n "Please give your username if different [$username]: "
        read -e
        [[ "$REPLY" ]] && username="$REPLY"
    fi
    


    if [ $use_java -eq 1 ]
    then
        local args=
        #get password
	[[ ! "$pass" ]] && read -sp "MyProxy Password? " pass
        [[ "$openId" ]] && args=$args" --oid $openId"
        [[ "$pass" ]] && args=$args" -P $pass"
        [[ "$username" ]] && args=$args" -l $username"
        
        echo -n $'\nRetrieving Credentials...' >&2
        if ! java $(proxy_to_java) -jar $MYPROXY_GETCERT $args --ca-directory $ESG_CERT_DIR --output $ESG_CREDENTIALS ; then        
            echo "Certificate could not be retrieved"
            exit 1
        fi
        echo "done!" >&2
    else
        args=`openid_to_myproxy_args $openId $username` || exit 1
        if ! myproxy-logon $args -b -o $ESG_CREDENTIALS
	then
            echo "Certificate could not be retrieved"
	    exit 1
        fi
	cp $HOME/.globus/certificates/* $ESG_CERT_DIR/	
    fi
}

openid_to_myproxy_args() {
  python - <<EOF || exit 1
import sys
import re
import xml.etree.ElementTree as ET
import urllib2
openid = "$1"
username = "$2" or re.sub(".*/", "", openid)
e = ET.parse(urllib2.urlopen(openid))
servs = [el for el in e.getiterator() if el.tag.endswith("Service")]
for serv in servs:
    servinfo = dict([(re.sub(".*}", "", c.tag), c.text)
                     for c in serv.getchildren()])
    try:
        if servinfo["Type"].endswith("myproxy-service"):
            m = re.match("socket://(.*):(.*)", servinfo["URI"])
            if m:
                host = m.group(1)
                port = m.group(2)
                print "-s %s -p %s -l %s" % (host, port, username)
                break
    except KeyError:
        continue
else:
    sys.stderr.write("myproxy service could not be found\n")
    sys.exit(1)
EOF
}

# check the certificate validity
check_cert() {
    if [[ ! -f "$ESG_CERT" || $force ]]; then
        #not there, just get it
        get_credentials
    elif which openssl &>/dev/null; then
        #check openssl and certificate
        if ! openssl x509 -checkend $CERT_EXPIRATION_WARNING -noout -in $ESG_CERT 2>/dev/null; then
            echo "The certificate expires in less than $((CERT_EXPIRATION_WARNING / 60 / 60)) hour(s). Renewing..."
            get_credentials
        else
            #ok, certificate is fine
            return 0
        fi
    fi
}

#
# Detect ESG credentials
#
find_credentials() {

    #is X509_USER_PROXY or $HOME/.esg/credential.pem
    if [[ -f "$ESG_CREDENTIALS" ]]; then
        # file found, proceed.
        ESG_CERT="$ESG_CREDENTIALS"
        ESG_KEY="$ESG_CREDENTIALS"
    elif [[ -f "$X509_USER_CERT" && -f "$X509_USER_KEY" ]]; then
        # second try, use these certificates.
        ESG_CERT="$X509_USER_CERT"
        ESG_KEY="$X509_USER_KEY"
    else
        # If credentials are not present, just point to where they should go 
        echo "No ESG Credentials found in $ESG_CREDENTIALS" >&2
            ESG_CERT="$ESG_CREDENTIALS"
            ESG_KEY="$ESG_CREDENTIALS"
            #they will be retrieved later one
    fi


    #chek openssl and certificate
    if (which openssl &>/dev/null); then
        if ( openssl version | grep 'OpenSSL 1\.0' ); then
            echo '** WARNING: ESGF Host certificate checking might not be compatible with OpenSSL 1.0+'
        fi
        check_cert || { (($?==1)); exit 1; }
    fi
    
    if [[ $CHECK_SERVER_CERT == "Yes" ]]; then
        [[ -d "$ESG_CERT_DIR" ]] || { echo "CA certs not found. Aborting."; exit 1; }
        PKI_WGET_OPTS="--ca-directory=$ESG_CERT_DIR"
    fi

    #some wget version complain if there's no file present
    [[ -f $COOKIE_JAR ]] || touch $COOKIE_JAR

    PKI_WGET_OPTS="$PKI_WGET_OPTS --certificate=$ESG_CERT --private-key=$ESG_KEY --save-cookies=$COOKIE_JAR --load-cookies=$COOKIE_JAR --ca-certificate=$ESG_CERT"

}

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

#Download data from node using cookies and not certificates.
download_http_sec()
{
  #The data to be downloaded.
  data=" $url"
  filename="$file"  

  #Wget args.
  if ((insecure)) 
  then
   wget_args=" --no-check-certificate --cookies=on  --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt " 
  else
   wget_args=" --ca-directory=$WGET_TRUSTED_CERTIFICATES --cookies=on --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt "  
  fi 

  if ((use_cookies_for_http_basic_auth_start)) || ((use_cookies_for_http_basic_auth)) 
  then
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
  fi
  
  if((force_TLSv1))
  then
   wget_args=" $wget_args"" --secure-protocol=TLSv1 "
  fi
  
  
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
    wget_args="$wget_args $ESGF_WGET_OPTS"
  fi  
  

  #use cookies for the next downloads
  use_cookies_for_http_basic_auth=1;
   
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "wget $wget_args $data\n"
  fi


  #Try to download the data. 
  command="wget $wget_args -O $filename $data"
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
      
  #Extract orp service from url ?
  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" == 1 )) && 
  if  echo "$http_resp" | grep -q "/esg-orp/"      
  then
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   orp_service=$(echo "$urls" | tr '\n' ' ' | cut -d' ' -f 2)


   #Use cookies for transaction with orp.
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
   
   #Download data using either http basic auth or http login form.
   if [[ "$openid_c" == */openid/  || "$openid_c" == */openid ]]
   then
    download_http_sec_open_id
   else
    download_http_sec_decide_service
   fi
  else  
   if    echo "$http_resp" | grep -q "401 Unauthorized"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || echo "$http_resp" | grep -q "Connection timed out."  \
      || echo "$http_resp" | grep -q "no-check-certificate"  \
      || (( $cmd_exit_status != 0 ))      
   then 
    echo "ERROR : http request to OpenID Relying Party service failed."
    failed=1
   fi
  fi
}


#Function that decides which implementaion of idp to use.
download_http_sec_decide_service()
{
  #find claimed id

  pos=$(echo "$openid_c" | egrep -o '/' | wc -l)
  username_c=$(echo "$openid_c"  | cut -d'/' -f "$(($pos + 1))")
  esgf_uri=$(echo "$openid_c" | egrep -o '/esgf-idp/openid/')

  host=$(echo "$openid_c"  | cut -d'/' -f 3)
  #test ceda first.

  if [[ -z "$esgf_uri" ]]
  then
   openid_c_tmp="https://""$host""/openid/"
  else
   openid_c_tmp="https://""$host""/esgf-idp/openid/" 
  fi

  command="wget "$openid_c_tmp" --no-check-certificate ${force_TLSv1:+--secure-protocol=TLSv1} -O-"
        
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
   command="$command $ESGF_WGET_OPTS"
  fi  
          
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "$command\n"
  fi
            

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
  

  if    echo "$http_resp" | grep -q "[application/xrds+xml]"  \
     && echo "$http_resp" | grep -q "200 OK"  \
     && (( cmd_exit_status == 0 ))       
  then
   openid_c=$openid_c_tmp
   download_http_sec_open_id
  else
   if [[ -z "$esgf_uri" ]]
   then
    echo "ERROR : HTTP request to OpenID Relying Party service failed."
    failed=1
   else
   download_http_sec_cl_id
   fi
  fi
}


download_http_sec_retry()
{
  echo -e "\nRetrying....\n"
  #Retry in case that last redirect did not work, this happens with older version of wget.
  command="wget $wget_args $data"
      
  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi   
   
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"

  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
   
  if    echo "$http_resp" | grep -q "401 Unauthorized"  \
     || echo "$http_resp" | grep -q "403: Forbidden"  \
     || echo "$http_resp" | grep -q "Connection timed out."  \
     || echo "$http_resp" | grep -q "no-check-certificate"  \
     || (( $cmd_exit_status != 0 ))      
  then 
   echo -e "\nERROR : Retry failed.\n"
   #rm "$filename"
   failed=1
  fi #if retry failed.
}

#Function for downloading data using the claimed id.
download_http_sec_cl_id()
{
  #Http request for sending openid to the orp service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\"  $wget_args -O- https://$orp_service/esg-orp/j_spring_openid_security_check.htm "

  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "wget $command\n"
  fi 
  
  
  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"

  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
    
  
  #Extract orp service from openid ?
  #Evaluate response.If redirected to idp service send the credentials.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( redirects == 2  )) && 
  if  echo "$http_resp" | grep -q "login.htm"  && (( cmd_exit_status == 0 ))   
  then 
  
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   idp_service=$(echo "$urls"  | tr '\n' ' ' | cut -d' ' -f 2) 
      
   command="wget --post-data  password=\"$password_c\" $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$idp_service/esgf-idp/idp/login.htm"
   

   #Debug message.
   if  ((debug))
   then
    echo -e "Executing:\n"
    echo -e "wget $command\n"
   fi 

   #Execution of command.
   http_resp=$(eval $command  2>&1)
   cmd_exit_status="$?"
      
   if ((debug))
   then
    echo -e "\nHTTP response:\n $http_resp\n"
   fi 
        
   #Evaluate response. 
   #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
   #(( "$redirects" != 5 )) \ 
   if    echo "$http_resp" | grep -q "text/html"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || (( cmd_exit_status != 0 ))        
   then 
    rm "$filename"
    download_http_sec_retry
   fi
 
  else
   echo "ERROR : HTTP request to OpenID Provider service failed."
   failed=1
  fi #if redirected to idp.  
}



download_http_sec_open_id()
{
  #Http request for sending openid to the orp web service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\" --header=\"esgf-idea-agent-type:basic_auth\" --http-user=\"$username_c\" --http-password=\"$password_c\"  $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$orp_service/esg-orp/j_spring_openid_security_check.htm "


  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi 

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 

  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" != 7 )) ||
  if   echo "$http_resp" | grep -q "text/html"  ||  (( $cmd_exit_status != 0 ))   
  then
   rm "$filename"
   download_http_sec_retry     
  fi #if error during http basic authentication. 
  
}


download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v} -c ${force_TLSv1:+--secure-protocol=TLSv1} $PKI_WGET_OPTS"
    
    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"
        
        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi
        
        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have. 
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count
        
        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                if ((use_http_sec))
                then
                 download_http_sec
                 if ((failed))
                 then
                  break
                 fi
                else
                 $wget -O "$file" $url || { failed=1; break; }  
                fi                
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi
                        
                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done
        
        if ((failed)); then
            echo "download failed"
            # most common failure is certificate expiration, so check this
            #if we have the pasword we can retrigger download
            ((!skip_security)) && [[ "$pass" ]] && check_cert
            unset failed
        fi
        
done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

http_basic_auth_func_info_message()
{
  echo  "********************************************************************************"
  echo  "*                                                                              *"
  echo  "* Note that new functionality to allow authentication without the need for     *"
  echo  "* certificates is available with this version of the wget script.  To enable,  *"
  echo  "* use the \"-H\" option and enter your OpenID and password when prompted:        *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -H [options...]                                     *"
  echo  "*                                                                              *"
  echo  "* For a full description of the available options use the help option:         *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -h                                                  *"
  echo  "*                                                                              *"
  echo  "********************************************************************************"
}

#
# MAIN
#

if ((!use_http_sec))
then 
 http_basic_auth_func_info_message
fi

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

((debug)) && cat<<EOF
** Debug info **
ESG_HOME=$ESG_HOME
ESG_CREDENTIALS=$ESG_CREDENTIALS
ESG_CERT_DIR=$ESG_CERT_DIR
** -- ** -- ** -- ** --

EOF


cat <<'EOF-MESSAGE'
Script created for 90 file(s)
(The count won't match if you manually edit this file!)



EOF-MESSAGE
sleep 1

check_os
((!skip_security)) && find_credentials

if ((use_http_sec))
then 
     
 if (( ! insecure))
 then 
  get_certificates
 fi

 #Cookies folder.
 COOKIES_FOLDER="$ESG_HOME/wget_cookies"
 
 if (( force ))
 then
  if [ -d $COOKIES_FOLDER ] 
  then
   rm -rf $COOKIES_FOLDER
  fi
 fi

 #Create cookies folder. 
 if [[ ! -d $COOKIES_FOLDER ]] 
 then
  mkdir $COOKIES_FOLDER
 fi
 
 if((! use_cookies_for_http_basic_auth_start))
 then

  #Read openid.
  if [[ ! -z "$openId" ]]
  then
   openid_c="$openId"
  elif ( (("$#" > 1)) || (("$#" == 1)) ) 
  then
   openid_c=$1
  else
   read -p    "Enter your openid : " openid_c
  fi
  
  
  #Read username.
  if [[ ! -z "$username_supplied" ]]
  then
   username_c="$username_supplied"
  elif (("$#" == 2))
  then
   username_c=$2
  elif [[ "$openid_c" == */openid/ || "$openid_c" == */openid ]]
  then
   read -p    "Enter username : " username_c
  fi
  
  #Read password.
  read -s -p "Enter password : " password_c
  echo -e "\n"

 fi #use cookies

fi #use_http_sec 


#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#clean the force parameter if here (at htis point we already have the certificate)
unset force

download

dedup_cache_


echo "done"
