#!/bin/bash
##############################################################################
# ESG Federation download script
#
# Template version: 1.2
# Generated by esg-dn1.nsc.liu.se - 2023/02/21 12:50:33
# Search URL: http://esg-dn1.nsc.liu.se/esg-search/wget/?distrib=false&dataset_id=CMIP6.RFMIP.EC-Earth-Consortium.EC-Earth3.piClim-control.r2i1p1f1.Amon.clt.gr.v20211201|esg-dn2.nsc.liu.se
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############" 
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=1.3.2
CACHE_FILE=.$(basename $0).status
openId=
search_url='http://esg-dn1.nsc.liu.se/esg-search/wget/?distrib=false&dataset_id=CMIP6.RFMIP.EC-Earth-Consortium.EC-Earth3.piClim-control.r2i1p1f1.Amon.clt.gr.v20211201|esg-dn2.nsc.liu.se'

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185001-185012.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185001-185012.nc' 'SHA256' '70d31fe375da0c8b4587c45326bc87dd771b625165785f1f55ff07396eff9e45'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185101-185112.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185101-185112.nc' 'SHA256' 'bdc0f78fee58dd74b26bc7bde4bec9eb32881d10b51ef599044a459749902997'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185201-185212.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185201-185212.nc' 'SHA256' '1abbe4436a60b8e7685e577e30a1d2476a1254dd2881ea64aba1579ef752a405'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185301-185312.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185301-185312.nc' 'SHA256' 'e9c2aefb2b46cc4b7f5f6ba49a7397a9c820238dc5453cc9f9721f9742b24028'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185401-185412.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185401-185412.nc' 'SHA256' 'c506e99ec0c824300e2f71a3bacbb066eb3e9b16ee7dc402a4e41ef351fc4beb'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185501-185512.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185501-185512.nc' 'SHA256' '8c8f52777f566378483c20438a927255dd657ee6341e1260b2c6c881933f452e'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185601-185612.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185601-185612.nc' 'SHA256' 'fd7f404807096daa112ab7eb5a3dda9c7b43f87c363d70c806428b8bdb0a2db6'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185701-185712.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185701-185712.nc' 'SHA256' '26d679b903c940d6c1db5aa708c4daaf9fe56d5c21d7f76d0ebcba6f07438412'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185801-185812.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185801-185812.nc' 'SHA256' '1e1fba3b7ee7bae35b87711a85bc824ebf092bf1f24b4dd2fc04a1a3218a2ee3'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185901-185912.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_185901-185912.nc' 'SHA256' 'ae9d4445f68504f63c1ec0a7d84c765d18fd4cae431c12722abaeef2089ad99b'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186001-186012.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186001-186012.nc' 'SHA256' '8e991fbf8a8372708b2ca98813f7d62c97b532a64a3c40eec6b9722738a959fc'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186101-186112.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186101-186112.nc' 'SHA256' 'e69039bec80e9fde8f67fe8d456863a9692c49d26fc598dd3376ed72b878def3'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186201-186212.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186201-186212.nc' 'SHA256' '34d85c5813e5e46f5bd6cdec6010361cc652572cebee574920c81b0b9ceae318'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186301-186312.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186301-186312.nc' 'SHA256' '1f1bf2e9e1a3de613ef527bae8a15307f0639cea56bc77cbef48c2aec7cb4047'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186401-186412.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186401-186412.nc' 'SHA256' '3d76e4ba0318632c8a4539f24d0551801e57ad1f01c784d38035616116e93123'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186501-186512.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186501-186512.nc' 'SHA256' 'a09f4149fb86d880dfb471316606145c00314698b6cd6c0f4a8c74cb85b50a4c'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186601-186612.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186601-186612.nc' 'SHA256' 'a3c4786d7052063531e78bc8afb3a01b864c73a2a029e32bcc42b0bdb1b0f9dd'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186701-186712.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186701-186712.nc' 'SHA256' 'b5a80f6f5da2f3303ce33809da83be98e1233e8ed001f05fa11938b3210f7275'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186801-186812.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186801-186812.nc' 'SHA256' 'b172be5d77e936ebd43d1f0db9d2846efbc7a57474b968acf9589abc00dab509'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186901-186912.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_186901-186912.nc' 'SHA256' '8fd69baef6b017b3f5d19a86d4156c5702d012b141df16c7d6a6bcbb0d92bdf6'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187001-187012.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187001-187012.nc' 'SHA256' '47548ddb54a59264f6038f32c289f1303f395b8ab60911acf348ad5664beea7f'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187101-187112.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187101-187112.nc' 'SHA256' 'a825db1a582a241a9311b07c507437099139d2d13a93195fb6126e0a068f6f05'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187201-187212.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187201-187212.nc' 'SHA256' '4e0953ca5870c96c7611958c9ff82bd5be6e8b609ee11ea40751cf34161a52be'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187301-187312.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187301-187312.nc' 'SHA256' 'd3ab925fe793047c274145f8418ca7b98ddcfce99fc1500628debda8be700ffd'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187401-187412.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187401-187412.nc' 'SHA256' 'dec8e7caeaf21a1a8eec4b7dbbf46e91da243daed457dd9b44a533817f8f54a5'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187501-187512.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187501-187512.nc' 'SHA256' '1f46918b59a434555e6959b1157029bbfbf2202f1c3c315dfe49bd080f29296f'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187601-187612.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187601-187612.nc' 'SHA256' '9c2ba77474a69ec563f601237a2416bf1460c9864235b2d5c8236541533dd6ed'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187701-187712.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187701-187712.nc' 'SHA256' 'ae1193b9a3d1a33d71c6d1b502948e556809eed73f5f3bf820dbafb9a81148ca'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187801-187812.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187801-187812.nc' 'SHA256' '9c226e38f99c291a5a1f7748b223d3d57c72e0112625f3d7ceae366202f45235'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187901-187912.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_187901-187912.nc' 'SHA256' '60992acf048568aa23fa5fb99634572dd825f231dda3749a161029562a04b65f'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188001-188012.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188001-188012.nc' 'SHA256' '8dbf78e80a7dd4eacc015abecbea6d8e4d15c8d8f015b3a24118e03930669964'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188101-188112.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188101-188112.nc' 'SHA256' 'ef5924703f1fc59af4849becf6edbd15e4e82d776186e8f100accb98bbbe921f'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188201-188212.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188201-188212.nc' 'SHA256' 'abf0714f3f68b65a9d1716e75903c4402471dba9faee73670d218258c7d9f08e'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188301-188312.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188301-188312.nc' 'SHA256' 'd25aa9cc516f9eebaf6cd04f1f3406f4b95691c0beb14656b5600803163a2b73'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188401-188412.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188401-188412.nc' 'SHA256' '175780be4efe6de4d5468947ef02f4b3bdfebc3fda8c4b6e47a59c307af87eca'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188501-188512.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188501-188512.nc' 'SHA256' 'c19ea4413c8b3c7ee40ac3f9c12dd43f8c025ebd606d942fde21bb9102894d12'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188601-188612.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188601-188612.nc' 'SHA256' '6df42da38f49acfc51d8943c2065c6c3ea4c9c696d39c74df1618eb52df33d7b'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188701-188712.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188701-188712.nc' 'SHA256' '8adfff260273c3850016422b59bf313e28771335f883008d3ff8b8241285258b'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188801-188812.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188801-188812.nc' 'SHA256' '99e871eba8c229b1c2b0b9d8b1f6ec84ed5670b49b8aa5f426676dc8b6bfca4e'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188901-188912.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_188901-188912.nc' 'SHA256' '8b91037d726bbb3979510fd5ead47587f21950ec363514989513a22e94187e6e'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189001-189012.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189001-189012.nc' 'SHA256' 'a50229a4fd8504df3c6c52efbe091785ce4d2fd74cc307150f417cd131736b04'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189101-189112.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189101-189112.nc' 'SHA256' 'f45a970270e7ca109fe5ec7cc6a1fdbeae39db94059166c1445068087a440ea2'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189201-189212.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189201-189212.nc' 'SHA256' '866bd2c24707b7cb9d255776e4380aa78b6c818968cea968b34aa18ac86a5a5f'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189301-189312.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189301-189312.nc' 'SHA256' '0e3264510986654ea7fad8f4e0beaf411794e764c1fb2376737538d925482b62'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189401-189412.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189401-189412.nc' 'SHA256' '17fb3bd487740ed826ee0cb7dcf252a8414489aae75ae81917409204f72be6cb'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189501-189512.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189501-189512.nc' 'SHA256' '2e0424bc33ae0e03283e849cbdc7bc74902dfdf7f5169f6e52cf65b290c0b85e'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189601-189612.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189601-189612.nc' 'SHA256' '974d50e0eeb2348c941ff369c7ed12c36cbe0706ebb7112ad64c04b776efdb2a'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189701-189712.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189701-189712.nc' 'SHA256' 'b24b8eaa31239b4e5b02a0973a3dc45a77711c4e0a4d5f0e6e809b6e033a54ca'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189801-189812.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189801-189812.nc' 'SHA256' '7e23548c5e5eee8f99a5c86b6bee336c45a4af18f216cbc9c714c191bbacc402'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189901-189912.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_189901-189912.nc' 'SHA256' 'cca325b2d115c6723a4af42098d3841e35c34362ebebd0f067e49a4bc7510e86'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190001-190012.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190001-190012.nc' 'SHA256' 'd047e1a92a57991f792e17b210f8a3da6e71e4e11573d4d3e43a6d8e9ea524e7'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190101-190112.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190101-190112.nc' 'SHA256' '0af085037b6f513f93916410e3b305c375b748cc534b53ba507db0ae09145af8'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190201-190212.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190201-190212.nc' 'SHA256' '86e647314e90bb4f4f01b3ea861d7327ea11d83a04fb323eb0fce2949779f172'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190301-190312.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190301-190312.nc' 'SHA256' '40b7d110277c26814e7aafe98dcca7231fb5cfa54f0e670ab3a949aa0ebdb514'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190401-190412.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190401-190412.nc' 'SHA256' 'dc63411f995f36a9598f906a931b1ec702f7d9973eabebed0bf8de2f50a7de3d'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190501-190512.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190501-190512.nc' 'SHA256' 'c9087bbce339b08e85c0a4cdf42fe78cef66b0ba5cf6f6d8a01709c21a0d4ef4'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190601-190612.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190601-190612.nc' 'SHA256' '1203e2c66d3cf7351f67965aa98a250528d8971b420084bf1042a1b085d037f0'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190701-190712.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190701-190712.nc' 'SHA256' '44eeeb81e3009e4a4480c340a5f92e4ac9c26264f6703981ff2e3c6179b881d7'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190801-190812.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190801-190812.nc' 'SHA256' 'b3690a59c90fcc0a2b0087a03184964345bfdfa8eca6dfbf1e42f51920010788'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190901-190912.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_190901-190912.nc' 'SHA256' '6c017ea9ca341a45cca8f0eacea15287506a1f568f2bf61ffe8d17a3735fce6f'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191001-191012.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191001-191012.nc' 'SHA256' 'fffa34b588d9e5e4c1b05bd93e068db67d6d50c8c4fbdf1457b1f38019461cb6'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191101-191112.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191101-191112.nc' 'SHA256' '388e357b44bd4bad21136f439da1ec474bf65df17710371dc7788261f3c68095'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191201-191212.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191201-191212.nc' 'SHA256' 'd1fbbc588266476ea7cf0b7ca7f4fc5c2a338ee3c5a798805d14589e04411d5f'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191301-191312.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191301-191312.nc' 'SHA256' '0d778124631687c71e2f1054da728398da6e6eee75797f5e1de63a6a9bed1495'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191401-191412.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191401-191412.nc' 'SHA256' 'a322ff13f2423726e2310ccf81d1187c79f5c4e869aa8d49a1a919699b646401'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191501-191512.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191501-191512.nc' 'SHA256' '4833421aaf8bfe0097874b58edb1743bfd912f6c6b2b97fafe13e377360abfaa'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191601-191612.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191601-191612.nc' 'SHA256' '4d0f0d96fe580e0b75762f7fff07c6c96b1c6a41027e7aba3d41350b5d2731e9'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191701-191712.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191701-191712.nc' 'SHA256' '76f41b18e21521abcbcc97c9c5f03f3d086e8b57e85d4d7b9b1face49515e4a4'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191801-191812.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191801-191812.nc' 'SHA256' 'df3987003162431fc8b8bf323715a15c8e19377f7fbf4a6ee7a4ff222b732b12'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191901-191912.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_191901-191912.nc' 'SHA256' 'a93fba1fc19467fb6f5b7f88bc3efde2a445e40a2bc542eb5f5d2bb013c36e25'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192001-192012.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192001-192012.nc' 'SHA256' '8c7bf3f5bc6976f174649eb29e4f7a1280f4b56c76d789d67180d2ff4db360fa'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192101-192112.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192101-192112.nc' 'SHA256' '81c3c074f720838274e4a01b9baf0d45c8fc64e4a24fe4f030b707d7a9935b62'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192201-192212.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192201-192212.nc' 'SHA256' '8ac6ad4721ef0475747c757e3922627f98282fb819d0b10e23dd4c8f9592d367'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192301-192312.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192301-192312.nc' 'SHA256' 'c5d07ab586bab24687b6771b7e20c2fa07dd42ed74f4bb0f61a3e66d94572abc'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192401-192412.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192401-192412.nc' 'SHA256' '7732e5a88c0205751cd02a57bc738b25e06782d370c6a341ba331118bfbd3f37'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192501-192512.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192501-192512.nc' 'SHA256' '79760cc4e587e471f3d035ef90c71ad9fa613fe17f96264d3375765e080924fa'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192601-192612.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192601-192612.nc' 'SHA256' '2c96965808720537d41025a718b7f51c2471560d2f2f7f5550172d807ded0bf6'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192701-192712.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192701-192712.nc' 'SHA256' '3dbbb7dbbbe9a6bb12004b5aed2cabda973f4434b3114b336be22597b562c7db'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192801-192812.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192801-192812.nc' 'SHA256' '6443e95fd42324b0c69e5be972d9a2e65ad06ec7ed07103aeef6bdee0c779844'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192901-192912.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_192901-192912.nc' 'SHA256' '984d2379e0c6541ab7400a0f6ae7fd920b6921b02203cf0034ecf9e36a9a7c69'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193001-193012.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193001-193012.nc' 'SHA256' '1e5ed4586b6a8aa27b9e93d5ca644f99ea986db3c2d34595ee794617c4c30205'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193101-193112.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193101-193112.nc' 'SHA256' 'ad12d985b71120d45858c29a0b8879545f62acf1376734b425c0ccbd180f7b38'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193201-193212.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193201-193212.nc' 'SHA256' 'a001c11c2e06d725c6b7cf667a1ce21dc5698816ce1c892f4afa49c8f9c50330'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193301-193312.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193301-193312.nc' 'SHA256' '7f040c24258352d801375eccf09a34e9b1efb407b1eb1427d20bc95cd9fa61d8'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193401-193412.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193401-193412.nc' 'SHA256' '7af74e72688137cdd063de3645c3c0119fe24a5103c129b8e1fcb5c06d854409'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193501-193512.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193501-193512.nc' 'SHA256' 'c6492052a84f199e39e668591df9f02518518ee77a6c19d6a1a24cb0a06c99fb'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193601-193612.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193601-193612.nc' 'SHA256' '803525e5eb553bc1e1c3f83fff0cc043063dbef77c1bf75d68881fcbd979c240'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193701-193712.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193701-193712.nc' 'SHA256' '51a5ccd969974b9080b819eaec94a016540e1f5f3df314c2bdc6bc436b6d7b63'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193801-193812.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193801-193812.nc' 'SHA256' '2cd3098381ce154a8e467184e3ec6651f10ebf18bc8976f65413fa3d9544dfcf'
'clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193901-193912.nc' 'http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot2/cmip6data/CMIP6/RFMIP/EC-Earth-Consortium/EC-Earth3/piClim-control/r2i1p1f1/Amon/clt/gr/v20211201/clt_Amon_EC-Earth3_piClim-control_r2i1p1f1_gr_193901-193912.nc' 'SHA256' '9ba888a4dbfc1af5911ce02347435b67e57721a21ab1d0c599b857a5e15f182a'
EOF--dataset.file.url.chksum_type.chksum
)"

# ESG_HOME should point to the directory containing ESG credentials.
#   Default is $HOME/.esg
ESG_HOME=${ESG_HOME:-$HOME/.esg}
[[ -d $ESG_HOME ]] || mkdir -p $ESG_HOME

ESG_CREDENTIALS=${X509_USER_PROXY:-$ESG_HOME/credentials.pem}
ESG_CERT_DIR=${X509_CERT_DIR:-$ESG_HOME/certificates}
MYPROXY_STATUS=$HOME/.MyProxyLogon
COOKIE_JAR=$ESG_HOME/cookies
MYPROXY_GETCERT=$ESG_HOME/getcert.jar
CERT_EXPIRATION_WARNING=$((60 * 60 * 8))   #Eight hour (in seconds)

WGET_TRUSTED_CERTIFICATES=$ESG_HOME/certificates


# Configure checking of server SSL certificates.
#   Disabling server certificate checking can resolve problems with myproxy
#   servers being out of sync with datanodes.
CHECK_SERVER_CERT=${CHECK_SERVER_CERT:-Yes}

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags] [openid] [username]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
    echo "For more information check the website: http://esgf.org/wiki/ESGF_wget"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts ':c:pfF:o:w:isuUndvqhHI:T' OPT; do
    case $OPT in
        H) skip_security=1 && use_http_sec=1;; #       : Authenticate with OpenID (username,) and password, without the need for a certificate.
        T) force_TLSv1=1;;              #       : Forces wget to use TLSv1. 
        c) ESG_CREDENTIALS="$OPTARG";;  #<cert> : use this certificate for authentication.
        f) force=1;;                    #       : force certificate retrieval (defaults to only once per day); for certificate-less authentication (see -H option), this flag will force login and refresh cookies.
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        o) openId="$OPTARG";;           #<openid>: Provide OpenID instead of interactively asking for it.
        I) username_supplied="$OPTARG";;    #<user_id> : Explicitly set user ID.  By default, the user ID is extracted from the last component of the OpenID URL.  Use this flag to override this behaviour.                   
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        s) skip_security=1 && use_cookies_for_http_basic_auth_start=1;;            #       : completely skip security. It will only work if the accessed data is not secured at all. -- works only if the accessed data is unsecured or a certificate exists or cookies are saved (latter applies to -H option only).
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi


#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    new_wget="$(wget "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0      
fi


##############################################################################
check_java() {
    if ! type java >& /dev/null; then
        echo "Java could not be found." >&2
        return 1
    fi
    if java -version 2>&1|grep openjdk >/dev/null; then
        openjdk=1;
    else
        openjdk=0;
    fi
    jversion=($(jversion=$(java -version 2>&1 | awk '/version/ {gsub("\"","");print $3}'); echo ${jversion//./ }))
    mVer=${jversion[1]}
    if [ $openjdk -eq 1 ]; then
        mVer=${jversion[0]}
        if ((mVer<5)); then
            echo "Openjdk detected. Version 9+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    else
    
        if ((mVer<5)); then
            echo "Java version 1.5+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    fi
}

check_myproxy_logon() {
    if ! type myproxy-logon >& /dev/null; then
	echo "myproxy-logon could not be found." >&2
	return 1
    fi
    echo "myproxy-logon found" >&2
}

proxy_to_java() {
    local proxy_user proxy_pass proxy_server proxy_port
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$http_proxy)
    local JAVA_PROXY=
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyPort=$proxy_port"
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$https_proxy)
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyPort=$proxy_port"
    
    echo "$JAVA_PROXY"
}

# get certificates from github
get_certificates() {
    # don't if this was already done today
    [[ -z $force && "$(find $ESG_CERT_DIR -type d -mtime -1 2>/dev/null)" ]] && return 0
    echo -n "Retrieving Federation Certificates..." >&2

    if ! wget -O $ESG_HOME/esg-truststore.ts --no-check-certificate https://github.com/ESGF/esgf-dist/raw/master/installer/certs/esg-truststore.ts; then
        echo "Could not fetch esg-truststore";
        return 1
    fi
    
    if ! wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar -O - -q | tar x -C $ESG_HOME; then
        #certificates tarred into esg_trusted_certificates. (if it breaks, let the user know why
        wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar
        echo "Could't update certs!" >&2
        return 1
    else
        #if here everythng went fine. Replace old cert with this ones    
        [[ -d $ESG_CERT_DIR ]] && rm -r $ESG_CERT_DIR || mkdir -p $(dirname $ESG_CERT_DIR)
        mv $ESG_HOME/esg_trusted_certificates $ESG_CERT_DIR
        touch $ESG_CERT_DIR
        echo "done!" >&2
    fi

}

# Retrieve ESG credentials
unset pass
get_credentials() {
    if check_java
    then
	use_java=1
    else	
	use_java=0
	echo "No suitable java for obtaining certificate - checking for myproxy-logon instead" >&2
	check_myproxy_logon || exit 1
    fi
    #get all certificates
    get_certificates

    if [[ -z "$(find $MYPROXY_GETCERT -type f -mtime -1 2>/dev/null)" ]]; then
        echo -n "(Downloading $MYPROXY_GETCERT... "
        mkdir -p $(dirname $MYPROXY_GETCERT)
        if wget -q --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/getcert.jar -O $MYPROXY_GETCERT;then
            echo 'done)'
            touch $MYPROXY_GETCERT
        else
            echo 'failed)'
        fi
    fi

    #if the user already defined one, use it
    if [[ -z $openId ]]; then
        #try to parse the last valid value if any
        [[ -f "$MYPROXY_STATUS" ]] && openId=$(awk -F= '/^OpenID/ {gsub("\\\\", ""); print $2}' $MYPROXY_STATUS)
        if [[ -z $openId ]]; then
            #no OpenID, we need to ask the user
            echo -n "Please give your OpenID (Example: https://myserver/example/username) ? "
        else
            #Allow the user to change it if desired
            echo -n "Please give your OpenID (hit ENTER to accept default: $openId)? "
        fi
        read -e
        [[ "$REPLY" ]] && openId="$REPLY"
    else
        ((verbose)) && echo "Using user defined OpenID $openId (to change use -o <open_id>)"
    fi

    if grep -q ceda.ac.uk <<<$openId; then
        username=${openId##*/}
        echo -n "Please give your username if different [$username]: "
        read -e
        [[ "$REPLY" ]] && username="$REPLY"
    fi
    


    if [ $use_java -eq 1 ]
    then
        local args=
        #get password
	[[ ! "$pass" ]] && read -sp "MyProxy Password? " pass
        [[ "$openId" ]] && args=$args" --oid $openId"
        [[ "$pass" ]] && args=$args" -P $pass"
        [[ "$username" ]] && args=$args" -l $username"
        
        echo -n $'\nRetrieving Credentials...' >&2
        if ! java $(proxy_to_java) -jar $MYPROXY_GETCERT $args --ca-directory $ESG_CERT_DIR --output $ESG_CREDENTIALS ; then        
            echo "Certificate could not be retrieved"
            exit 1
        fi
        echo "done!" >&2
    else
        args=`openid_to_myproxy_args $openId $username` || exit 1
        if ! myproxy-logon $args -b -o $ESG_CREDENTIALS
	then
            echo "Certificate could not be retrieved"
	    exit 1
        fi
	cp $HOME/.globus/certificates/* $ESG_CERT_DIR/	
    fi
}

openid_to_myproxy_args() {
  python - <<EOF || exit 1
import sys
import re
import xml.etree.ElementTree as ET
import urllib2
openid = "$1"
username = "$2" or re.sub(".*/", "", openid)
e = ET.parse(urllib2.urlopen(openid))
servs = [el for el in e.getiterator() if el.tag.endswith("Service")]
for serv in servs:
    servinfo = dict([(re.sub(".*}", "", c.tag), c.text)
                     for c in serv.getchildren()])
    try:
        if servinfo["Type"].endswith("myproxy-service"):
            m = re.match("socket://(.*):(.*)", servinfo["URI"])
            if m:
                host = m.group(1)
                port = m.group(2)
                print "-s %s -p %s -l %s" % (host, port, username)
                break
    except KeyError:
        continue
else:
    sys.stderr.write("myproxy service could not be found\n")
    sys.exit(1)
EOF
}

# check the certificate validity
check_cert() {
    if [[ ! -f "$ESG_CERT" || $force ]]; then
        #not there, just get it
        get_credentials
    elif which openssl &>/dev/null; then
        #check openssl and certificate
        if ! openssl x509 -checkend $CERT_EXPIRATION_WARNING -noout -in $ESG_CERT 2>/dev/null; then
            echo "The certificate expires in less than $((CERT_EXPIRATION_WARNING / 60 / 60)) hour(s). Renewing..."
            get_credentials
        else
            #ok, certificate is fine
            return 0
        fi
    fi
}

#
# Detect ESG credentials
#
find_credentials() {

    #is X509_USER_PROXY or $HOME/.esg/credential.pem
    if [[ -f "$ESG_CREDENTIALS" ]]; then
        # file found, proceed.
        ESG_CERT="$ESG_CREDENTIALS"
        ESG_KEY="$ESG_CREDENTIALS"
    elif [[ -f "$X509_USER_CERT" && -f "$X509_USER_KEY" ]]; then
        # second try, use these certificates.
        ESG_CERT="$X509_USER_CERT"
        ESG_KEY="$X509_USER_KEY"
    else
        # If credentials are not present, just point to where they should go 
        echo "No ESG Credentials found in $ESG_CREDENTIALS" >&2
            ESG_CERT="$ESG_CREDENTIALS"
            ESG_KEY="$ESG_CREDENTIALS"
            #they will be retrieved later one
    fi


    #chek openssl and certificate
    if (which openssl &>/dev/null); then
        if ( openssl version | grep 'OpenSSL 1\.0' ); then
            echo '** WARNING: ESGF Host certificate checking might not be compatible with OpenSSL 1.0+'
        fi
        check_cert || { (($?==1)); exit 1; }
    fi
    
    if [[ $CHECK_SERVER_CERT == "Yes" ]]; then
        [[ -d "$ESG_CERT_DIR" ]] || { echo "CA certs not found. Aborting."; exit 1; }
        PKI_WGET_OPTS="--ca-directory=$ESG_CERT_DIR"
    fi

    #some wget version complain if there's no file present
    [[ -f $COOKIE_JAR ]] || touch $COOKIE_JAR

    PKI_WGET_OPTS="$PKI_WGET_OPTS --certificate=$ESG_CERT --private-key=$ESG_KEY --save-cookies=$COOKIE_JAR --load-cookies=$COOKIE_JAR --ca-certificate=$ESG_CERT"

}

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

#Download data from node using cookies and not certificates.
download_http_sec()
{
  #The data to be downloaded.
  data=" $url"
  filename="$file"  

  #Wget args.
  if ((insecure)) 
  then
   wget_args=" --no-check-certificate --cookies=on  --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt " 
  else
   wget_args=" --ca-directory=$WGET_TRUSTED_CERTIFICATES --cookies=on --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt "  
  fi 

  if ((use_cookies_for_http_basic_auth_start)) || ((use_cookies_for_http_basic_auth)) 
  then
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
  fi
  
  if((force_TLSv1))
  then
   wget_args=" $wget_args"" --secure-protocol=TLSv1 "
  fi
  
  
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
    wget_args="$wget_args $ESGF_WGET_OPTS"
  fi  
  

  #use cookies for the next downloads
  use_cookies_for_http_basic_auth=1;
   
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "wget $wget_args $data\n"
  fi


  #Try to download the data. 
  command="wget $wget_args -O $filename $data"
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
      
  #Extract orp service from url ?
  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" == 1 )) && 
  if  echo "$http_resp" | grep -q "/esg-orp/"      
  then
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   orp_service=$(echo "$urls" | tr '\n' ' ' | cut -d' ' -f 2)


   #Use cookies for transaction with orp.
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
   
   #Download data using either http basic auth or http login form.
   if [[ "$openid_c" == */openid/  || "$openid_c" == */openid ]]
   then
    download_http_sec_open_id
   else
    download_http_sec_decide_service
   fi
  else  
   if    echo "$http_resp" | grep -q "401 Unauthorized"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || echo "$http_resp" | grep -q "Connection timed out."  \
      || echo "$http_resp" | grep -q "no-check-certificate"  \
      || (( $cmd_exit_status != 0 ))      
   then 
    echo "ERROR : http request to OpenID Relying Party service failed."
    failed=1
   fi
  fi
}


#Function that decides which implementaion of idp to use.
download_http_sec_decide_service()
{
  #find claimed id

  pos=$(echo "$openid_c" | egrep -o '/' | wc -l)
  username_c=$(echo "$openid_c"  | cut -d'/' -f "$(($pos + 1))")
  esgf_uri=$(echo "$openid_c" | egrep -o '/esgf-idp/openid/')

  host=$(echo "$openid_c"  | cut -d'/' -f 3)
  #test ceda first.

  if [[ -z "$esgf_uri" ]]
  then
   openid_c_tmp="https://""$host""/openid/"
  else
   openid_c_tmp="https://""$host""/esgf-idp/openid/" 
  fi

  command="wget "$openid_c_tmp" --no-check-certificate ${force_TLSv1:+--secure-protocol=TLSv1} -O-"
        
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
   command="$command $ESGF_WGET_OPTS"
  fi  
          
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "$command\n"
  fi
            

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
  

  if    echo "$http_resp" | grep -q "[application/xrds+xml]"  \
     && echo "$http_resp" | grep -q "200 OK"  \
     && (( cmd_exit_status == 0 ))       
  then
   openid_c=$openid_c_tmp
   download_http_sec_open_id
  else
   if [[ -z "$esgf_uri" ]]
   then
    echo "ERROR : HTTP request to OpenID Relying Party service failed."
    failed=1
   else
   download_http_sec_cl_id
   fi
  fi
}


download_http_sec_retry()
{
  echo -e "\nRetrying....\n"
  #Retry in case that last redirect did not work, this happens with older version of wget.
  command="wget $wget_args $data"
      
  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi   
   
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"

  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
   
  if    echo "$http_resp" | grep -q "401 Unauthorized"  \
     || echo "$http_resp" | grep -q "403: Forbidden"  \
     || echo "$http_resp" | grep -q "Connection timed out."  \
     || echo "$http_resp" | grep -q "no-check-certificate"  \
     || (( $cmd_exit_status != 0 ))      
  then 
   echo -e "\nERROR : Retry failed.\n"
   #rm "$filename"
   failed=1
  fi #if retry failed.
}

#Function for downloading data using the claimed id.
download_http_sec_cl_id()
{
  #Http request for sending openid to the orp service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\"  $wget_args -O- https://$orp_service/esg-orp/j_spring_openid_security_check.htm "

  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "wget $command\n"
  fi 
  
  
  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"

  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
    
  
  #Extract orp service from openid ?
  #Evaluate response.If redirected to idp service send the credentials.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( redirects == 2  )) && 
  if  echo "$http_resp" | grep -q "login.htm"  && (( cmd_exit_status == 0 ))   
  then 
  
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   idp_service=$(echo "$urls"  | tr '\n' ' ' | cut -d' ' -f 2) 
      
   command="wget --post-data  password=\"$password_c\" $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$idp_service/esgf-idp/idp/login.htm"
   

   #Debug message.
   if  ((debug))
   then
    echo -e "Executing:\n"
    echo -e "wget $command\n"
   fi 

   #Execution of command.
   http_resp=$(eval $command  2>&1)
   cmd_exit_status="$?"
      
   if ((debug))
   then
    echo -e "\nHTTP response:\n $http_resp\n"
   fi 
        
   #Evaluate response. 
   #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
   #(( "$redirects" != 5 )) \ 
   if    echo "$http_resp" | grep -q "text/html"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || (( cmd_exit_status != 0 ))        
   then 
    rm "$filename"
    download_http_sec_retry
   fi
 
  else
   echo "ERROR : HTTP request to OpenID Provider service failed."
   failed=1
  fi #if redirected to idp.  
}



download_http_sec_open_id()
{
  #Http request for sending openid to the orp web service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\" --header=\"esgf-idea-agent-type:basic_auth\" --http-user=\"$username_c\" --http-password=\"$password_c\"  $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$orp_service/esg-orp/j_spring_openid_security_check.htm "


  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi 

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 

  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" != 7 )) ||
  if   echo "$http_resp" | grep -q "text/html"  ||  (( $cmd_exit_status != 0 ))   
  then
   rm "$filename"
   download_http_sec_retry     
  fi #if error during http basic authentication. 
  
}


download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v} -c ${force_TLSv1:+--secure-protocol=TLSv1} $PKI_WGET_OPTS"
    
    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"
        
        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi
        
        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have. 
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count
        
        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                if ((use_http_sec))
                then
                 download_http_sec
                 if ((failed))
                 then
                  break
                 fi
                else
                 $wget -O "$file" $url || { failed=1; break; }  
                fi                
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi
                        
                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done
        
        if ((failed)); then
            echo "download failed"
            # most common failure is certificate expiration, so check this
            #if we have the pasword we can retrigger download
            ((!skip_security)) && [[ "$pass" ]] && check_cert
            unset failed
        fi
        
done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

http_basic_auth_func_info_message()
{
  echo  "********************************************************************************"
  echo  "*                                                                              *"
  echo  "* Note that new functionality to allow authentication without the need for     *"
  echo  "* certificates is available with this version of the wget script.  To enable,  *"
  echo  "* use the \"-H\" option and enter your OpenID and password when prompted:        *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -H [options...]                                     *"
  echo  "*                                                                              *"
  echo  "* For a full description of the available options use the help option:         *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -h                                                  *"
  echo  "*                                                                              *"
  echo  "********************************************************************************"
}

#
# MAIN
#

if ((!use_http_sec))
then 
 http_basic_auth_func_info_message
fi

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

((debug)) && cat<<EOF
** Debug info **
ESG_HOME=$ESG_HOME
ESG_CREDENTIALS=$ESG_CREDENTIALS
ESG_CERT_DIR=$ESG_CERT_DIR
** -- ** -- ** -- ** --

EOF


cat <<'EOF-MESSAGE'
Script created for 90 file(s)
(The count won't match if you manually edit this file!)



EOF-MESSAGE
sleep 1

check_os
((!skip_security)) && find_credentials

if ((use_http_sec))
then 
     
 if (( ! insecure))
 then 
  get_certificates
 fi

 #Cookies folder.
 COOKIES_FOLDER="$ESG_HOME/wget_cookies"
 
 if (( force ))
 then
  if [ -d $COOKIES_FOLDER ] 
  then
   rm -rf $COOKIES_FOLDER
  fi
 fi

 #Create cookies folder. 
 if [[ ! -d $COOKIES_FOLDER ]] 
 then
  mkdir $COOKIES_FOLDER
 fi
 
 if((! use_cookies_for_http_basic_auth_start))
 then

  #Read openid.
  if [[ ! -z "$openId" ]]
  then
   openid_c="$openId"
  elif ( (("$#" > 1)) || (("$#" == 1)) ) 
  then
   openid_c=$1
  else
   read -p    "Enter your openid : " openid_c
  fi
  
  
  #Read username.
  if [[ ! -z "$username_supplied" ]]
  then
   username_c="$username_supplied"
  elif (("$#" == 2))
  then
   username_c=$2
  elif [[ "$openid_c" == */openid/ || "$openid_c" == */openid ]]
  then
   read -p    "Enter username : " username_c
  fi
  
  #Read password.
  read -s -p "Enter password : " password_c
  echo -e "\n"

 fi #use cookies

fi #use_http_sec 


#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#clean the force parameter if here (at htis point we already have the certificate)
unset force

download

dedup_cache_


echo "done"
