#!/usr/bin/env bash

if [ -f .env ]
then
  export $(cat .env | xargs)
fi

# first remove any existing zipfile and list of files
if [ -f ziplist.txt ]
then
  rm ziplist.txt
fi
if [ -f fair_calibrate.zip ]
then
  rm fair_calibrate.zip
fi

> ziplist.txt
find input -type d -name __pycache__ -prune -o -print >> ziplist.txt
find output >> ziplist.txt
find plots >> ziplist.txt
find data >> ziplist.txt
find r_scripts >> ziplist.txt
ls -1 *.* >> ziplist.txt
ls -1 run >> ziplist.txt
ls -1 .env >> ziplist.txt

zip fair_calibrate.zip -@ < ziplist.txt
