name: fair2.1-calibrate
channels:
  - chrisroadmap
  - conda-forge
  - defaults
dependencies:
  - climateforcing
  - ffmpeg
  - h5py
  - ipywidgets
  - jupyter
  - matplotlib
  - nbstripout
  - netCDF4
  - numpy
  - openpyxl
  - pandas
  - pooch
  - scipy
  - tqdm
  - xarray
  - xlrd
