name: fair-calibrate
channels:
  - chrisroadmap
  - conda-forge
dependencies:
  - python==3.11.10
  - black
  - fair==2.1.3
  - flake8
  - flexparser<0.4  # pint dependency but v0.4 breaks it, see https://github.com/hgrecco/pint/issues/2074
  - h5py
  - isort
  - matplotlib
  - mscorefonts
  - netCDF4
  - numpy
  - pandas
  - pint==0.24.3  # aneris dependency
  - pooch
  - python-dotenv
  - scikit-learn
  - scipy
  - scmdata
  - tqdm
  - xarray
  - pip
  - pip:
    - aneris-iamc[units]
