name: fair-calibrate
channels:
  - conda-forge
dependencies:
  - python==3.11
  - black
  - fair==2.2.0
  - flake8
  - isort
  - matplotlib
  - mscorefonts
  - numpy
  - pandas
  - pooch
  - python-dotenv
  - scikit-learn
  - scipy
  - tqdm
  - xarray
