name: fair-calibrate
channels:
  - chrisroadmap
  - conda-forge
  - defaults
dependencies:
  - black
  - fair==2.1.2
  - flake8
  - h5py
  - isort
  - matplotlib
  - netCDF4
  - numpy
  - pandas
  - pooch
  - python-dotenv
  - r-base
  - r-devtools
  - scikit-learn
  - scipy
  - scmdata
  - tqdm
  - xarray
  - pip
  - pip:
    - aneris-iamc[units]
