name: fair-calibrate
channels:
  - chrisroadmap
  - conda-forge
dependencies:
  - python==3.11.10
  - black
  - fair==2.2.2
  - flake8
  - h5py
  - isort
  - matplotlib
  - mscorefonts
  - netCDF4
  - numpy
  - pandas
  - pooch
  - python-dotenv
  - scikit-learn
  - scipy
  - scmdata
  - tqdm
  - xarray
  - pip
  - pip:
    - aneris-iamc[units]==0.3.1
