name: fair-calibrate
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - flake8
  - h5py
  - isort
  - matplotlib
  - netCDF4
  - numpy
  - pandas
  - pooch
  - python-dotenv
  - scipy
  - scmdata
  - tqdm
  - xarray
  - pip
  - pip:
    - aneris-iamc[units]
    - fair==2.1.0
