name: fair-calibrate
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - flake8
  - isort
  - matplotlib
  - netCDF4
  - numpy
  - pandas
  - pooch
  - python-dotenv
  - scipy
  - tqdm
  - xarray
  - pip
  - pip:
    - fair==2.1.0
