name: fair-calibrate
channels:
  - conda-forge
  - defaults
dependencies:
  - ffmpeg
  - ipywidgets
  - jupyter
  - matplotlib
  - nbstripout
  - netCDF4
  - numpy
  - openpyxl
  - pandas
  - pooch
  - scipy
  - tqdm
  - xarray
  - xlrd
  - pip
  - pip:
    - fair==2.1.0
