species_types = [
    'co2 ffi',
    'co2 afolu',
    'co2',
    'ch4',
    'n2o',
    'cfc-11',
    'other halogen',
    'f-gas',
    'sulfur',
    'black carbon',
    'organic carbon',
    'other slcf',
    'nox aviation',
    'ozone',
    'aerosol-radiation interactions',
    'aerosol-cloud interactions',
    'contrails',
    'lapsi',
    'stratospheric water vapour',
    'land use'
    'volcanic',
    'solar',
    'unspecified'
]

valid_input_modes = {
    'co2 ffi': ['emissions'],
    'co2 afolu': ['emissions'],
    'co2': ['calculated', 'concentration', 'forcing'],
    'ch4': ['emissions', 'concentration', 'forcing'],
    'n2o': ['emissions', 'concentration', 'forcing'],
    'cfc-11': ['emissions', 'concentration', 'forcing'],
    'other halogen': ['emissions', 'concentration', 'forcing'],
    'f-gas': ['emissions', 'concentration', 'forcing'],
    'sulfur': ['emissions'],
    'black carbon': ['emissions'],
    'organic carbon': ['emissions'],
    'other slcf': ['emissions'],
    'nox aviation': ['emissions'],
    'ozone': ['calculated', 'forcing'],
    'aerosol-radiation interactions': ['calculated', 'forcing'],
    'aerosol-cloud interactions': ['calculated', 'forcing'],
    'contrails': ['calculated', 'forcing'],
    'lapsi': ['calculated', 'forcing'],
    'stratospheric water vapour': ['calculated', 'forcing'],
    'land use': ['calculated', 'forcing'],
    'volcanic': ['forcing'],
    'solar': ['forcing'],
    'unspecified': ['forcing'],
}

multiple_allowed = {
    'co2 ffi': False,
    'co2 afolu': False,
    'co2': False,
    'ch4': False,
    'n2o': False,
    'cfc-11': False,
    'other halogen': True,
    'f-gas': True,
    'sulfur': False,
    'black carbon': False,
    'organic carbon': False,
    'other slcf': True,
    'nox aviation': False,
    'ozone': False,
    'aerosol-radiation interactions': False,
    'aerosol-cloud interactions': False,
    'contrails': False,
    'lapsi': False,
    'stratospheric water vapour': False,
    'land use': False,
    'volcanic': False,
    'solar': False,
    'unspecified': True,
}
